package com.smartaiwriter.app.util

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.runtime.compositionLocalOf

/** Reactive app language state — changes trigger recomposition */
object AppLanguageState {
    var languageCode by mutableStateOf("en")
}

data class Strings(
    // Bottom nav
    val navCreate: String,
    val navSummary: String,
    val navTranslate: String,
    val navHistory: String,
    val navSettings: String,

    // Home screen
    val homeTitle: String,
    val homeSubtitle: String,
    val dailyCredits: String,
    val tokensRemaining: String,
    val whatToWrite: String,
    val topicPlaceholder: String,
    val uploadFile: String,
    val uploadSupported: String,
    val outputFormat: String,
    val language: String,
    val generateDocuments: String,
    val minCharsHint: String,

    // Processing
    val processing: String,
    val generating: String,

    // Result
    val yourDocuments: String,
    val filesReady: String,
    val download: String,
    val downloadAll: String,
    val preview: String,
    val editDocument: String,
    val share: String,
    val createNew: String,
    val savedToDownloads: String,
    val saveFailed: String,
    val noFiles: String,

    // Settings
    val settings: String,
    val customizeExperience: String,
    val appearance: String,
    val theme: String,
    val light: String,
    val dark: String,
    val auto: String,
    val appLanguage: String,
    val languageHint: String,
    val usage: String,
    val dailyTokenUsage: String,
    val resetsAtMidnight: String,
    val premium: String,
    val premiumDesc: String,
    val soon: String,
    val legal: String,
    val privacyPolicy: String,
    val privacyDesc: String,
    val termsOfService: String,
    val termsDesc: String,
    val sendFeedback: String,
    val feedbackDesc: String,

    // History
    val history: String,
    val noHistory: String,

    // Translate
    val translate: String,
    val aiTranslator: String,
    val translateSubtitle: String,
    val from: String,
    val to: String,
    val sourceLanguage: String,
    val targetLanguage: String,
    val enterText: String,
    val parsingFile: String,

    // Summarize
    val summarize: String,
    val aiSummarizer: String,
    val summarizeSubtitle: String,
    val enterTextToSummarize: String,
    val outputLanguage: String,
    val howItWorks: String,
    val howItWorksDesc: String,

    // History
    val clearHistory: String,
    val clearHistoryConfirm: String,
    val clear: String,
    val cancel: String,
    val clearAll: String,
    val historyEmpty: String,

    // Processing
    val analyzingInput: String,
    val checkingLimits: String,
    val generatingWithAi: String,
    val preparingEditor: String,
    val dailyLimitReached: String,
    val generationFailed: String,
    val errorOccurred: String,
    val goBack: String,

    // Splash
    val getStarted: String,
    val welcomeTo: String,
    val aiWriter: String,
    val splashSubtitle: String,
    val splashFeature1: String,
    val splashFeature2: String,
    val splashFeature3: String,

    // Footer
    val appVersion: String,
    val poweredBy: String
)

val EnglishStrings = Strings(
    navCreate = "Create", navSummary = "Summary", navTranslate = "Translate", navHistory = "History", navSettings = "Settings",
    homeTitle = "AI Writer", homeSubtitle = "Create something amazing",
    dailyCredits = "Daily Credits", tokensRemaining = "tokens remaining",
    whatToWrite = "What to write", topicPlaceholder = "Describe your document topic, e.g.\n\"A business plan for an eco-friendly café\"",
    uploadFile = "Upload a file (optional)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Output format", language = "Language", generateDocuments = "Generate Documents",
    minCharsHint = "Enter at least 3 characters or upload a file",
    processing = "Processing", generating = "Generating your documents…",
    yourDocuments = "Your Documents", filesReady = "Your files are ready!",
    download = "Download", downloadAll = "Download All", preview = "Preview", editDocument = "Edit Document",
    share = "Share", createNew = "Create New",
    savedToDownloads = "Saved to Downloads", saveFailed = "Save failed", noFiles = "No files generated",
    settings = "Settings", customizeExperience = "Customize your experience",
    appearance = "Appearance", theme = "Theme", light = "Light", dark = "Dark", auto = "Auto",
    appLanguage = "App Language", languageHint = "Changes app display language",
    usage = "Usage", dailyTokenUsage = "Daily Token Usage", resetsAtMidnight = "Resets at midnight",
    premium = "Premium", premiumDesc = "Unlimited tokens & more features", soon = "Soon",
    legal = "Legal", privacyPolicy = "Privacy Policy", privacyDesc = "How we handle your data",
    termsOfService = "Terms of Service", termsDesc = "Rules for using AI Writer",
    sendFeedback = "Send Feedback", feedbackDesc = "Help us improve AI Writer",
    history = "History", noHistory = "No documents yet",
    translate = "Translate", aiTranslator = "AI Translator", translateSubtitle = "Translate documents or text with AI",
    from = "From", to = "To", sourceLanguage = "Source Language", targetLanguage = "Target Language",
    enterText = "Enter or paste text…", parsingFile = "Parsing file…",
    summarize = "Summarize", aiSummarizer = "AI Summarizer", summarizeSubtitle = "Summarize documents or text with AI",
    enterTextToSummarize = "Enter or paste text to summarize…", outputLanguage = "Output Language",
    howItWorks = "How it works", howItWorksDesc = "AI extracts key points from your text, targeting 30-40% of original length.",
    clearHistory = "Clear History", clearHistoryConfirm = "Delete all history entries? This cannot be undone.",
    clear = "Clear", cancel = "Cancel", clearAll = "Clear All", historyEmpty = "Generated documents will appear here",
    analyzingInput = "Analyzing input", checkingLimits = "Checking usage limits",
    generatingWithAi = "Generating with AI", preparingEditor = "Preparing editor",
    dailyLimitReached = "Daily token limit reached. Try again tomorrow.",
    generationFailed = "Generation failed", errorOccurred = "An error occurred", goBack = "Go Back",
    getStarted = "Get Started", welcomeTo = "Welcome to", aiWriter = "AI Writer",
    splashSubtitle = "Create beautiful documents\nwith the power of AI",
    splashFeature1 = "Generate PDF, Word, PPT & Excel",
    splashFeature2 = "Translate documents in 32 languages",
    splashFeature3 = "AI-powered summaries & editing",
    appVersion = "AI Writer v3.0.0", poweredBy = "Powered by Longcat AI"
)

val ArabicStrings = Strings(
    navCreate = "إنشاء", navSummary = "ملخص", navTranslate = "ترجمة", navHistory = "السجل", navSettings = "الإعدادات",
    homeTitle = "AI Writer", homeSubtitle = "أنشئ شيئاً مذهلاً",
    dailyCredits = "الرصيد اليومي", tokensRemaining = "رمز متبقي",
    whatToWrite = "ماذا تريد أن تكتب", topicPlaceholder = "صف موضوع المستند، مثلاً\n\"خطة عمل لمقهى صديق للبيئة\"",
    uploadFile = "ارفع ملفاً (اختياري)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "صيغة الإخراج", language = "اللغة", generateDocuments = "إنشاء المستندات",
    minCharsHint = "أدخل 3 أحرف على الأقل أو ارفع ملفاً",
    processing = "جاري المعالجة", generating = "جاري إنشاء مستنداتك…",
    yourDocuments = "مستنداتك", filesReady = "ملفاتك جاهزة!",
    download = "تحميل", downloadAll = "تحميل الكل", preview = "معاينة", editDocument = "تعديل المستند",
    share = "مشاركة", createNew = "إنشاء جديد",
    savedToDownloads = "تم الحفظ في التنزيلات", saveFailed = "فشل الحفظ", noFiles = "لا توجد ملفات",
    settings = "الإعدادات", customizeExperience = "خصّص تجربتك",
    appearance = "المظهر", theme = "السمة", light = "فاتح", dark = "داكن", auto = "تلقائي",
    appLanguage = "لغة التطبيق", languageHint = "تغيير لغة عرض التطبيق",
    usage = "الاستخدام", dailyTokenUsage = "الاستخدام اليومي", resetsAtMidnight = "يتم إعادة التعيين عند منتصف الليل",
    premium = "مميز", premiumDesc = "رموز غير محدودة وميزات أكثر", soon = "قريباً",
    legal = "قانوني", privacyPolicy = "سياسة الخصوصية", privacyDesc = "كيف نتعامل مع بياناتك",
    termsOfService = "شروط الخدمة", termsDesc = "قواعد استخدام AI Writer",
    sendFeedback = "إرسال ملاحظات", feedbackDesc = "ساعدنا في تحسين AI Writer",
    history = "السجل", noHistory = "لا توجد مستندات بعد",
    translate = "ترجمة", aiTranslator = "مترجم AI", translateSubtitle = "ترجم المستندات أو النصوص بالذكاء الاصطناعي",
    from = "من", to = "إلى", sourceLanguage = "اللغة المصدر", targetLanguage = "اللغة الهدف",
    enterText = "أدخل أو الصق نص…", parsingFile = "جاري تحليل الملف…",
    summarize = "تلخيص", aiSummarizer = "ملخص AI", summarizeSubtitle = "لخص المستندات أو النصوص بالذكاء الاصطناعي",
    enterTextToSummarize = "أدخل أو الصق نصاً لتلخيصه…", outputLanguage = "لغة الإخراج",
    howItWorks = "كيف يعمل", howItWorksDesc = "يستخرج الذكاء الاصطناعي النقاط الرئيسية من نصك بنسبة 30-40٪ من الطول الأصلي.",
    clearHistory = "مسح السجل", clearHistoryConfirm = "حذف جميع السجلات؟ لا يمكن التراجع.",
    clear = "مسح", cancel = "إلغاء", clearAll = "مسح الكل", historyEmpty = "ستظهر المستندات المنشأة هنا",
    analyzingInput = "تحليل المدخلات", checkingLimits = "التحقق من حدود الاستخدام",
    generatingWithAi = "الإنشاء بالذكاء الاصطناعي", preparingEditor = "تحضير المحرر",
    dailyLimitReached = "تم الوصول للحد اليومي. حاول غداً.",
    generationFailed = "فشل الإنشاء", errorOccurred = "حدث خطأ", goBack = "رجوع",
    getStarted = "ابدأ الآن", welcomeTo = "مرحباً بك في", aiWriter = "AI Writer",
    splashSubtitle = "أنشئ مستندات جميلة\nبقوة الذكاء الاصطناعي",
    splashFeature1 = "إنشاء PDF و Word و PPT و Excel",
    splashFeature2 = "ترجمة المستندات بـ 32 لغة",
    splashFeature3 = "تلخيص وتحرير بالذكاء الاصطناعي",
    appVersion = "AI Writer v3.0.0", poweredBy = "مدعوم بـ Longcat AI"
)

val SpanishStrings = Strings(
    navCreate = "Crear", navSummary = "Resumen", navTranslate = "Traducir", navHistory = "Historial", navSettings = "Ajustes",
    homeTitle = "AI Writer", homeSubtitle = "Crea algo increíble",
    dailyCredits = "Créditos diarios", tokensRemaining = "tokens restantes",
    whatToWrite = "Qué escribir", topicPlaceholder = "Describe el tema del documento, ej.\n\"Un plan de negocio para un café ecológico\"",
    uploadFile = "Subir archivo (opcional)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Formato de salida", language = "Idioma", generateDocuments = "Generar documentos",
    minCharsHint = "Ingresa al menos 3 caracteres o sube un archivo",
    processing = "Procesando", generating = "Generando tus documentos…",
    yourDocuments = "Tus documentos", filesReady = "¡Tus archivos están listos!",
    download = "Descargar", downloadAll = "Descargar todo", preview = "Vista previa", editDocument = "Editar documento",
    share = "Compartir", createNew = "Crear nuevo",
    savedToDownloads = "Guardado en Descargas", saveFailed = "Error al guardar", noFiles = "No hay archivos",
    settings = "Ajustes", customizeExperience = "Personaliza tu experiencia",
    appearance = "Apariencia", theme = "Tema", light = "Claro", dark = "Oscuro", auto = "Auto",
    appLanguage = "Idioma de la app", languageHint = "Cambiar idioma de la interfaz",
    usage = "Uso", dailyTokenUsage = "Uso diario de tokens", resetsAtMidnight = "Se reinicia a medianoche",
    premium = "Premium", premiumDesc = "Tokens ilimitados y más funciones", soon = "Pronto",
    legal = "Legal", privacyPolicy = "Política de privacidad", privacyDesc = "Cómo manejamos tus datos",
    termsOfService = "Términos de servicio", termsDesc = "Reglas de uso de AI Writer",
    sendFeedback = "Enviar comentarios", feedbackDesc = "Ayúdanos a mejorar AI Writer",
    history = "Historial", noHistory = "Aún no hay documentos",
    translate = "Traducir", aiTranslator = "Traductor AI", translateSubtitle = "Traduce documentos o texto con IA",
    from = "De", to = "A", sourceLanguage = "Idioma de origen", targetLanguage = "Idioma de destino",
    enterText = "Ingresa o pega texto…", parsingFile = "Analizando archivo…",
    summarize = "Resumir", aiSummarizer = "Resumidor AI", summarizeSubtitle = "Resume documentos o texto con IA",
    enterTextToSummarize = "Ingresa o pega texto para resumir…", outputLanguage = "Idioma de salida",
    howItWorks = "Cómo funciona", howItWorksDesc = "La IA extrae los puntos clave de tu texto, apuntando al 30-40% del largo original.",
    clearHistory = "Borrar historial", clearHistoryConfirm = "¿Eliminar todo el historial? No se puede deshacer.",
    clear = "Borrar", cancel = "Cancelar", clearAll = "Borrar todo", historyEmpty = "Los documentos generados aparecerán aquí",
    analyzingInput = "Analizando entrada", checkingLimits = "Verificando límites",
    generatingWithAi = "Generando con IA", preparingEditor = "Preparando editor",
    dailyLimitReached = "Límite diario alcanzado. Intenta mañana.",
    generationFailed = "Error al generar", errorOccurred = "Ocurrió un error", goBack = "Volver",
    getStarted = "Empezar", welcomeTo = "Bienvenido a", aiWriter = "AI Writer",
    splashSubtitle = "Crea documentos hermosos\ncon el poder de la IA",
    splashFeature1 = "Genera PDF, Word, PPT y Excel",
    splashFeature2 = "Traduce documentos en 32 idiomas",
    splashFeature3 = "Resúmenes y edición con IA",
    appVersion = "AI Writer v3.0.0", poweredBy = "Desarrollado con Longcat AI"
)

val FrenchStrings = Strings(
    navCreate = "Créer", navSummary = "Résumé", navTranslate = "Traduire", navHistory = "Historique", navSettings = "Paramètres",
    homeTitle = "AI Writer", homeSubtitle = "Créez quelque chose d'incroyable",
    dailyCredits = "Crédits quotidiens", tokensRemaining = "jetons restants",
    whatToWrite = "Que voulez-vous écrire", topicPlaceholder = "Décrivez le sujet, ex.\n\"Un business plan pour un café écologique\"",
    uploadFile = "Télécharger un fichier (optionnel)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Format de sortie", language = "Langue", generateDocuments = "Générer les documents",
    minCharsHint = "Entrez au moins 3 caractères ou téléchargez un fichier",
    processing = "Traitement", generating = "Génération de vos documents…",
    yourDocuments = "Vos documents", filesReady = "Vos fichiers sont prêts!",
    download = "Télécharger", downloadAll = "Tout télécharger", preview = "Aperçu", editDocument = "Modifier le document",
    share = "Partager", createNew = "Nouveau",
    savedToDownloads = "Enregistré dans Téléchargements", saveFailed = "Échec de sauvegarde", noFiles = "Aucun fichier",
    settings = "Paramètres", customizeExperience = "Personnalisez votre expérience",
    appearance = "Apparence", theme = "Thème", light = "Clair", dark = "Sombre", auto = "Auto",
    appLanguage = "Langue de l'app", languageHint = "Changer la langue de l'interface",
    usage = "Utilisation", dailyTokenUsage = "Utilisation quotidienne", resetsAtMidnight = "Réinitialisation à minuit",
    premium = "Premium", premiumDesc = "Jetons illimités et plus", soon = "Bientôt",
    legal = "Juridique", privacyPolicy = "Politique de confidentialité", privacyDesc = "Comment nous gérons vos données",
    termsOfService = "Conditions d'utilisation", termsDesc = "Règles d'utilisation d'AI Writer",
    sendFeedback = "Envoyer des commentaires", feedbackDesc = "Aidez-nous à améliorer AI Writer",
    history = "Historique", noHistory = "Aucun document pour l'instant",
    translate = "Traduire", aiTranslator = "Traducteur AI", translateSubtitle = "Traduisez des documents ou du texte avec l'IA",
    from = "De", to = "Vers", sourceLanguage = "Langue source", targetLanguage = "Langue cible",
    enterText = "Entrez ou collez du texte…", parsingFile = "Analyse du fichier…",
    summarize = "Résumer", aiSummarizer = "Résumeur AI", summarizeSubtitle = "Résumez des documents ou du texte avec l'IA",
    enterTextToSummarize = "Entrez ou collez du texte à résumer…", outputLanguage = "Langue de sortie",
    howItWorks = "Comment ça marche", howItWorksDesc = "L'IA extrait les points clés de votre texte, visant 30-40% de la longueur originale.",
    clearHistory = "Effacer l'historique", clearHistoryConfirm = "Supprimer tout l'historique ? Cette action est irréversible.",
    clear = "Effacer", cancel = "Annuler", clearAll = "Tout effacer", historyEmpty = "Les documents générés apparaîtront ici",
    analyzingInput = "Analyse de l'entrée", checkingLimits = "Vérification des limites",
    generatingWithAi = "Génération avec l'IA", preparingEditor = "Préparation de l'éditeur",
    dailyLimitReached = "Limite quotidienne atteinte. Réessayez demain.",
    generationFailed = "Échec de génération", errorOccurred = "Une erreur est survenue", goBack = "Retour",
    getStarted = "Commencer", welcomeTo = "Bienvenue sur", aiWriter = "AI Writer",
    splashSubtitle = "Créez de beaux documents\navec la puissance de l'IA",
    splashFeature1 = "Générez PDF, Word, PPT et Excel",
    splashFeature2 = "Traduisez dans 32 langues",
    splashFeature3 = "Résumés et édition par IA",
    appVersion = "AI Writer v3.0.0", poweredBy = "Propulsé par Longcat AI"
)

val GermanStrings = Strings(
    navCreate = "Erstellen", navSummary = "Zusammen.", navTranslate = "Übersetzen", navHistory = "Verlauf", navSettings = "Einstellung.",
    homeTitle = "AI Writer", homeSubtitle = "Erstelle etwas Großartiges",
    dailyCredits = "Tägliches Guthaben", tokensRemaining = "Tokens übrig",
    whatToWrite = "Was schreiben", topicPlaceholder = "Beschreibe das Thema, z.B.\n\"Ein Businessplan für ein Öko-Café\"",
    uploadFile = "Datei hochladen (optional)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Ausgabeformat", language = "Sprache", generateDocuments = "Dokumente erstellen",
    minCharsHint = "Gib mindestens 3 Zeichen ein oder lade eine Datei hoch",
    processing = "Verarbeitung", generating = "Deine Dokumente werden erstellt…",
    yourDocuments = "Deine Dokumente", filesReady = "Deine Dateien sind fertig!",
    download = "Download", downloadAll = "Alle herunterladen", preview = "Vorschau", editDocument = "Dokument bearbeiten",
    share = "Teilen", createNew = "Neu erstellen",
    savedToDownloads = "In Downloads gespeichert", saveFailed = "Speichern fehlgeschlagen", noFiles = "Keine Dateien",
    settings = "Einstellungen", customizeExperience = "Passe dein Erlebnis an",
    appearance = "Darstellung", theme = "Design", light = "Hell", dark = "Dunkel", auto = "Auto",
    appLanguage = "App-Sprache", languageHint = "Anzeigesprache ändern",
    usage = "Nutzung", dailyTokenUsage = "Tägliche Token-Nutzung", resetsAtMidnight = "Setzt um Mitternacht zurück",
    premium = "Premium", premiumDesc = "Unbegrenzte Tokens & mehr", soon = "Bald",
    legal = "Rechtliches", privacyPolicy = "Datenschutz", privacyDesc = "Wie wir mit deinen Daten umgehen",
    termsOfService = "Nutzungsbedingungen", termsDesc = "Regeln für die Nutzung",
    sendFeedback = "Feedback senden", feedbackDesc = "Hilf uns AI Writer zu verbessern",
    history = "Verlauf", noHistory = "Noch keine Dokumente",
    translate = "Übersetzen", aiTranslator = "AI Übersetzer", translateSubtitle = "Übersetze Dokumente oder Text mit KI",
    from = "Von", to = "Nach", sourceLanguage = "Ausgangssprache", targetLanguage = "Zielsprache",
    enterText = "Text eingeben oder einfügen…", parsingFile = "Datei wird analysiert…",
    summarize = "Zusammenfassen", aiSummarizer = "AI Zusammenfasser", summarizeSubtitle = "Fasse Dokumente oder Text mit KI zusammen",
    enterTextToSummarize = "Text zum Zusammenfassen eingeben…", outputLanguage = "Ausgabesprache",
    howItWorks = "So funktioniert's", howItWorksDesc = "KI extrahiert Kernpunkte aus deinem Text (ca. 30-40% der Originallänge).",
    clearHistory = "Verlauf löschen", clearHistoryConfirm = "Gesamten Verlauf löschen? Dies kann nicht rückgängig gemacht werden.",
    clear = "Löschen", cancel = "Abbrechen", clearAll = "Alles löschen", historyEmpty = "Erstellte Dokumente erscheinen hier",
    analyzingInput = "Eingabe analysieren", checkingLimits = "Limits prüfen",
    generatingWithAi = "Mit KI generieren", preparingEditor = "Editor vorbereiten",
    dailyLimitReached = "Tägliches Limit erreicht. Versuche es morgen.",
    generationFailed = "Generierung fehlgeschlagen", errorOccurred = "Ein Fehler ist aufgetreten", goBack = "Zurück",
    getStarted = "Loslegen", welcomeTo = "Willkommen bei", aiWriter = "AI Writer",
    splashSubtitle = "Erstelle schöne Dokumente\nmit der Kraft der KI",
    splashFeature1 = "PDF, Word, PPT & Excel erstellen",
    splashFeature2 = "Dokumente in 32 Sprachen übersetzen",
    splashFeature3 = "KI-gestützte Zusammenfassungen & Bearbeitung",
    appVersion = "AI Writer v3.0.0", poweredBy = "Powered by Longcat AI"
)

val TurkishStrings = Strings(
    navCreate = "Oluştur", navSummary = "Özet", navTranslate = "Çeviri", navHistory = "Geçmiş", navSettings = "Ayarlar",
    homeTitle = "AI Writer", homeSubtitle = "Harika bir şey oluştur",
    dailyCredits = "Günlük Kredi", tokensRemaining = "jeton kaldı",
    whatToWrite = "Ne yazmak istiyorsun", topicPlaceholder = "Belge konusunu açıklayın, örn.\n\"Eko-dostu bir kafe için iş planı\"",
    uploadFile = "Dosya yükle (isteğe bağlı)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Çıktı formatı", language = "Dil", generateDocuments = "Belge Oluştur",
    minCharsHint = "En az 3 karakter girin veya dosya yükleyin",
    processing = "İşleniyor", generating = "Belgeleriniz oluşturuluyor…",
    yourDocuments = "Belgeleriniz", filesReady = "Dosyalarınız hazır!",
    download = "İndir", downloadAll = "Hepsini İndir", preview = "Önizleme", editDocument = "Belgeyi Düzenle",
    share = "Paylaş", createNew = "Yeni Oluştur",
    savedToDownloads = "İndirilenler'e kaydedildi", saveFailed = "Kaydetme başarısız", noFiles = "Dosya yok",
    settings = "Ayarlar", customizeExperience = "Deneyimini özelleştir",
    appearance = "Görünüm", theme = "Tema", light = "Açık", dark = "Koyu", auto = "Otomatik",
    appLanguage = "Uygulama Dili", languageHint = "Arayüz dilini değiştir",
    usage = "Kullanım", dailyTokenUsage = "Günlük Token Kullanımı", resetsAtMidnight = "Gece yarısı sıfırlanır",
    premium = "Premium", premiumDesc = "Sınırsız token ve daha fazlası", soon = "Yakında",
    legal = "Yasal", privacyPolicy = "Gizlilik Politikası", privacyDesc = "Verilerinizi nasıl işliyoruz",
    termsOfService = "Kullanım Şartları", termsDesc = "AI Writer kullanım kuralları",
    sendFeedback = "Geri Bildirim Gönder", feedbackDesc = "AI Writer'ı geliştirmemize yardım edin",
    history = "Geçmiş", noHistory = "Henüz belge yok",
    translate = "Çeviri", aiTranslator = "AI Çevirmen", translateSubtitle = "Belgeleri veya metni yapay zeka ile çevirin",
    from = "Kaynak", to = "Hedef", sourceLanguage = "Kaynak Dil", targetLanguage = "Hedef Dil",
    enterText = "Metin girin veya yapıştırın…", parsingFile = "Dosya analiz ediliyor…",
    summarize = "Özetle", aiSummarizer = "AI Özetleyici", summarizeSubtitle = "Belgeleri veya metni yapay zeka ile özetleyin",
    enterTextToSummarize = "Özetlenecek metni girin…", outputLanguage = "Çıktı Dili",
    howItWorks = "Nasıl çalışır", howItWorksDesc = "Yapay zeka metninizden anahtar noktaları çıkarır, orijinal uzunluğun %30-40'ını hedefler.",
    clearHistory = "Geçmişi Temizle", clearHistoryConfirm = "Tüm geçmiş silinsin mi? Bu geri alınamaz.",
    clear = "Temizle", cancel = "İptal", clearAll = "Tümünü Temizle", historyEmpty = "Oluşturulan belgeler burada görünecek",
    analyzingInput = "Girdi analiz ediliyor", checkingLimits = "Limitler kontrol ediliyor",
    generatingWithAi = "Yapay zeka ile oluşturuluyor", preparingEditor = "Editör hazırlanıyor",
    dailyLimitReached = "Günlük limit aşıldı. Yarın tekrar deneyin.",
    generationFailed = "Oluşturma başarısız", errorOccurred = "Bir hata oluştu", goBack = "Geri Dön",
    getStarted = "Başla", welcomeTo = "Hoş geldiniz", aiWriter = "AI Writer",
    splashSubtitle = "Yapay zekanın gücüyle\ngüzel belgeler oluşturun",
    splashFeature1 = "PDF, Word, PPT ve Excel oluşturun",
    splashFeature2 = "32 dilde belge çevirin",
    splashFeature3 = "Yapay zeka ile özetleme ve düzenleme",
    appVersion = "AI Writer v3.0.0", poweredBy = "Longcat AI ile desteklenmektedir"
)

val PersianStrings = Strings(
    navCreate = "ایجاد", navSummary = "خلاصه", navTranslate = "ترجمه", navHistory = "تاریخچه", navSettings = "تنظیمات",
    homeTitle = "AI Writer", homeSubtitle = "چیز شگفت‌انگیزی بسازید",
    dailyCredits = "اعتبار روزانه", tokensRemaining = "توکن باقیمانده",
    whatToWrite = "چه بنویسم", topicPlaceholder = "موضوع سند را توصیف کنید\n\"طرح کسب و کار برای کافه سبز\"",
    uploadFile = "آپلود فایل (اختیاری)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "فرمت خروجی", language = "زبان", generateDocuments = "ایجاد اسناد",
    minCharsHint = "حداقل ۳ کاراکتر وارد کنید یا فایل آپلود کنید",
    processing = "در حال پردازش", generating = "در حال ایجاد اسناد شما…",
    yourDocuments = "اسناد شما", filesReady = "فایل‌های شما آماده‌اند!",
    download = "دانلود", downloadAll = "دانلود همه", preview = "پیش‌نمایش", editDocument = "ویرایش سند",
    share = "اشتراک", createNew = "ایجاد جدید",
    savedToDownloads = "در دانلودها ذخیره شد", saveFailed = "ذخیره ناموفق", noFiles = "فایلی نیست",
    settings = "تنظیمات", customizeExperience = "تجربه خود را سفارشی کنید",
    appearance = "ظاهر", theme = "تم", light = "روشن", dark = "تاریک", auto = "خودکار",
    appLanguage = "زبان برنامه", languageHint = "تغییر زبان نمایش",
    usage = "مصرف", dailyTokenUsage = "مصرف روزانه توکن", resetsAtMidnight = "نیمه‌شب بازنشانی می‌شود",
    premium = "ویژه", premiumDesc = "توکن نامحدود و امکانات بیشتر", soon = "به‌زودی",
    legal = "حقوقی", privacyPolicy = "سیاست حریم خصوصی", privacyDesc = "نحوه مدیریت داده‌های شما",
    termsOfService = "شرایط خدمات", termsDesc = "قوانین استفاده از AI Writer",
    sendFeedback = "ارسال بازخورد", feedbackDesc = "به ما کمک کنید AI Writer را بهبود دهیم",
    history = "تاریخچه", noHistory = "هنوز سندی نیست",
    translate = "ترجمه", aiTranslator = "مترجم AI", translateSubtitle = "اسناد یا متن را با هوش مصنوعی ترجمه کنید",
    from = "از", to = "به", sourceLanguage = "زبان مبدا", targetLanguage = "زبان مقصد",
    enterText = "متن وارد کنید…", parsingFile = "در حال تحلیل فایل…",
    summarize = "خلاصه‌سازی", aiSummarizer = "خلاصه‌ساز AI", summarizeSubtitle = "اسناد یا متن را با هوش مصنوعی خلاصه کنید",
    enterTextToSummarize = "متن برای خلاصه‌سازی وارد کنید…", outputLanguage = "زبان خروجی",
    howItWorks = "نحوه کار", howItWorksDesc = "هوش مصنوعی نکات کلیدی را از متن شما استخراج می‌کند (۳۰-۴۰٪ طول اصلی).",
    clearHistory = "پاک کردن تاریخچه", clearHistoryConfirm = "همه تاریخچه پاک شود؟ این عمل قابل بازگشت نیست.",
    clear = "پاک کردن", cancel = "لغو", clearAll = "پاک کردن همه", historyEmpty = "اسناد ایجاد شده اینجا نمایش داده می‌شوند",
    analyzingInput = "تحلیل ورودی", checkingLimits = "بررسی محدودیت‌ها",
    generatingWithAi = "ایجاد با هوش مصنوعی", preparingEditor = "آماده‌سازی ویرایشگر",
    dailyLimitReached = "محدودیت روزانه پر شد. فردا دوباره تلاش کنید.",
    generationFailed = "ایجاد ناموفق", errorOccurred = "خطایی رخ داد", goBack = "بازگشت",
    getStarted = "شروع", welcomeTo = "خوش آمدید به", aiWriter = "AI Writer",
    splashSubtitle = "اسناد زیبا بسازید\nبا قدرت هوش مصنوعی",
    splashFeature1 = "ایجاد PDF، Word، PPT و Excel",
    splashFeature2 = "ترجمه اسناد به ۳۲ زبان",
    splashFeature3 = "خلاصه‌سازی و ویرایش با هوش مصنوعی",
    appVersion = "AI Writer v3.0.0", poweredBy = "ارائه شده توسط Longcat AI"
)

val ChineseStrings = Strings(
    navCreate = "创建", navSummary = "摘要", navTranslate = "翻译", navHistory = "历史", navSettings = "设置",
    homeTitle = "AI Writer", homeSubtitle = "创造精彩内容",
    dailyCredits = "每日额度", tokensRemaining = "剩余令牌",
    whatToWrite = "写什么", topicPlaceholder = "描述文档主题，例如\n\"环保咖啡馆商业计划\"",
    uploadFile = "上传文件（可选）", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "输出格式", language = "语言", generateDocuments = "生成文档",
    minCharsHint = "请输入至少3个字符或上传文件",
    processing = "处理中", generating = "正在生成您的文档…",
    yourDocuments = "您的文档", filesReady = "文件已准备就绪！",
    download = "下载", downloadAll = "全部下载", preview = "预览", editDocument = "编辑文档",
    share = "分享", createNew = "新建",
    savedToDownloads = "已保存到下载", saveFailed = "保存失败", noFiles = "没有文件",
    settings = "设置", customizeExperience = "自定义体验",
    appearance = "外观", theme = "主题", light = "浅色", dark = "深色", auto = "自动",
    appLanguage = "应用语言", languageHint = "更改界面显示语言",
    usage = "使用情况", dailyTokenUsage = "每日令牌使用", resetsAtMidnight = "午夜重置",
    premium = "高级版", premiumDesc = "无限令牌和更多功能", soon = "即将推出",
    legal = "法律", privacyPolicy = "隐私政策", privacyDesc = "我们如何处理您的数据",
    termsOfService = "服务条款", termsDesc = "AI Writer使用规则",
    sendFeedback = "发送反馈", feedbackDesc = "帮助我们改进AI Writer",
    history = "历史", noHistory = "暂无文档",
    translate = "翻译", aiTranslator = "AI翻译器", translateSubtitle = "用AI翻译文档或文本",
    from = "从", to = "到", sourceLanguage = "源语言", targetLanguage = "目标语言",
    enterText = "输入或粘贴文本…", parsingFile = "正在解析文件…",
    summarize = "摘要", aiSummarizer = "AI摘要器", summarizeSubtitle = "用AI总结文档或文本",
    enterTextToSummarize = "输入或粘贴要总结的文本…", outputLanguage = "输出语言",
    howItWorks = "工作原理", howItWorksDesc = "AI从您的文本中提取关键点，目标为原文长度的30-40%。",
    clearHistory = "清除历史", clearHistoryConfirm = "删除所有历史记录？此操作不可撤销。",
    clear = "清除", cancel = "取消", clearAll = "全部清除", historyEmpty = "生成的文档将显示在这里",
    analyzingInput = "分析输入", checkingLimits = "检查使用限额",
    generatingWithAi = "AI生成中", preparingEditor = "准备编辑器",
    dailyLimitReached = "已达每日限额，请明天再试。",
    generationFailed = "生成失败", errorOccurred = "发生错误", goBack = "返回",
    getStarted = "开始使用", welcomeTo = "欢迎使用", aiWriter = "AI Writer",
    splashSubtitle = "用AI的力量\n创建精美文档",
    splashFeature1 = "生成PDF、Word、PPT和Excel",
    splashFeature2 = "支持32种语言翻译",
    splashFeature3 = "AI摘要和编辑",
    appVersion = "AI Writer v3.0.0", poweredBy = "由Longcat AI提供支持"
)

val JapaneseStrings = Strings(
    navCreate = "作成", navSummary = "要約", navTranslate = "翻訳", navHistory = "履歴", navSettings = "設定",
    homeTitle = "AI Writer", homeSubtitle = "素晴らしいものを作ろう",
    dailyCredits = "日次クレジット", tokensRemaining = "トークン残り",
    whatToWrite = "何を書く", topicPlaceholder = "文書のトピックを説明してください\n例：「エコカフェのビジネスプラン」",
    uploadFile = "ファイルをアップロード（任意）", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "出力形式", language = "言語", generateDocuments = "文書を生成",
    minCharsHint = "3文字以上入力するかファイルをアップロード",
    processing = "処理中", generating = "文書を生成しています…",
    yourDocuments = "あなたの文書", filesReady = "ファイルの準備ができました！",
    download = "ダウンロード", downloadAll = "すべてダウンロード", preview = "プレビュー", editDocument = "文書を編集",
    share = "共有", createNew = "新規作成",
    savedToDownloads = "ダウンロードに保存しました", saveFailed = "保存に失敗", noFiles = "ファイルがありません",
    settings = "設定", customizeExperience = "体験をカスタマイズ",
    appearance = "外観", theme = "テーマ", light = "ライト", dark = "ダーク", auto = "自動",
    appLanguage = "アプリの言語", languageHint = "表示言語を変更",
    usage = "使用量", dailyTokenUsage = "日次トークン使用量", resetsAtMidnight = "深夜にリセット",
    premium = "プレミアム", premiumDesc = "無制限トークンと追加機能", soon = "近日公開",
    legal = "法的情報", privacyPolicy = "プライバシーポリシー", privacyDesc = "データの取り扱い方法",
    termsOfService = "利用規約", termsDesc = "AI Writerの利用ルール",
    sendFeedback = "フィードバックを送信", feedbackDesc = "AI Writerの改善にご協力ください",
    history = "履歴", noHistory = "まだ文書がありません",
    translate = "翻訳", aiTranslator = "AI翻訳", translateSubtitle = "AIで文書やテキストを翻訳",
    from = "翻訳元", to = "翻訳先", sourceLanguage = "ソース言語", targetLanguage = "ターゲット言語",
    enterText = "テキストを入力または貼り付け…", parsingFile = "ファイルを解析中…",
    summarize = "要約", aiSummarizer = "AI要約", summarizeSubtitle = "AIで文書やテキストを要約",
    enterTextToSummarize = "要約するテキストを入力…", outputLanguage = "出力言語",
    howItWorks = "仕組み", howItWorksDesc = "AIがテキストから重要なポイントを抽出し、原文の30-40%の長さにまとめます。",
    clearHistory = "履歴を消去", clearHistoryConfirm = "すべての履歴を削除しますか？元に戻せません。",
    clear = "消去", cancel = "キャンセル", clearAll = "すべて消去", historyEmpty = "生成した文書がここに表示されます",
    analyzingInput = "入力を分析中", checkingLimits = "使用制限を確認",
    generatingWithAi = "AIで生成中", preparingEditor = "エディタを準備中",
    dailyLimitReached = "日次制限に達しました。明日もう一度お試しください。",
    generationFailed = "生成に失敗", errorOccurred = "エラーが発生しました", goBack = "戻る",
    getStarted = "始める", welcomeTo = "ようこそ", aiWriter = "AI Writer",
    splashSubtitle = "AIの力で\n美しい文書を作成",
    splashFeature1 = "PDF、Word、PPT、Excelを生成",
    splashFeature2 = "32言語で文書を翻訳",
    splashFeature3 = "AI要約と編集",
    appVersion = "AI Writer v3.0.0", poweredBy = "Longcat AI 搭載"
)

val KoreanStrings = Strings(
    navCreate = "만들기", navSummary = "요약", navTranslate = "번역", navHistory = "기록", navSettings = "설정",
    homeTitle = "AI Writer", homeSubtitle = "멋진 것을 만들어보세요",
    dailyCredits = "일일 크레딧", tokensRemaining = "토큰 남음",
    whatToWrite = "무엇을 쓸까요", topicPlaceholder = "문서 주제를 설명하세요\n예: \"친환경 카페 사업 계획\"",
    uploadFile = "파일 업로드 (선택)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "출력 형식", language = "언어", generateDocuments = "문서 생성",
    minCharsHint = "3자 이상 입력하거나 파일을 업로드하세요",
    processing = "처리 중", generating = "문서를 생성하고 있습니다…",
    yourDocuments = "내 문서", filesReady = "파일이 준비되었습니다!",
    download = "다운로드", downloadAll = "모두 다운로드", preview = "미리보기", editDocument = "문서 편집",
    share = "공유", createNew = "새로 만들기",
    savedToDownloads = "다운로드에 저장됨", saveFailed = "저장 실패", noFiles = "파일 없음",
    settings = "설정", customizeExperience = "경험 맞춤설정",
    appearance = "외관", theme = "테마", light = "라이트", dark = "다크", auto = "자동",
    appLanguage = "앱 언어", languageHint = "표시 언어 변경",
    usage = "사용량", dailyTokenUsage = "일일 토큰 사용량", resetsAtMidnight = "자정에 초기화",
    premium = "프리미엄", premiumDesc = "무제한 토큰 및 추가 기능", soon = "곧 출시",
    legal = "법적 정보", privacyPolicy = "개인정보처리방침", privacyDesc = "데이터 처리 방법",
    termsOfService = "이용약관", termsDesc = "AI Writer 이용 규칙",
    sendFeedback = "피드백 보내기", feedbackDesc = "AI Writer 개선에 도움을 주세요",
    history = "기록", noHistory = "아직 문서가 없습니다",
    translate = "번역", aiTranslator = "AI 번역기", translateSubtitle = "AI로 문서나 텍스트를 번역하세요",
    from = "출발어", to = "도착어", sourceLanguage = "원본 언어", targetLanguage = "대상 언어",
    enterText = "텍스트를 입력하거나 붙여넣기…", parsingFile = "파일 분석 중…",
    summarize = "요약", aiSummarizer = "AI 요약기", summarizeSubtitle = "AI로 문서나 텍스트를 요약하세요",
    enterTextToSummarize = "요약할 텍스트를 입력…", outputLanguage = "출력 언어",
    howItWorks = "작동 방식", howItWorksDesc = "AI가 텍스트에서 핵심 포인트를 추출합니다 (원문 길이의 30-40%).",
    clearHistory = "기록 삭제", clearHistoryConfirm = "모든 기록을 삭제하시겠습니까? 되돌릴 수 없습니다.",
    clear = "삭제", cancel = "취소", clearAll = "모두 삭제", historyEmpty = "생성된 문서가 여기에 표시됩니다",
    analyzingInput = "입력 분석 중", checkingLimits = "사용 한도 확인",
    generatingWithAi = "AI로 생성 중", preparingEditor = "편집기 준비 중",
    dailyLimitReached = "일일 한도에 도달했습니다. 내일 다시 시도하세요.",
    generationFailed = "생성 실패", errorOccurred = "오류가 발생했습니다", goBack = "돌아가기",
    getStarted = "시작하기", welcomeTo = "환영합니다", aiWriter = "AI Writer",
    splashSubtitle = "AI의 힘으로\n아름다운 문서를 만드세요",
    splashFeature1 = "PDF, Word, PPT, Excel 생성",
    splashFeature2 = "32개 언어로 문서 번역",
    splashFeature3 = "AI 요약 및 편집",
    appVersion = "AI Writer v3.0.0", poweredBy = "Longcat AI 제공"
)

val RussianStrings = Strings(
    navCreate = "Создать", navSummary = "Резюме", navTranslate = "Перевод", navHistory = "История", navSettings = "Настройки",
    homeTitle = "AI Writer", homeSubtitle = "Создавайте удивительное",
    dailyCredits = "Дневной лимит", tokensRemaining = "токенов осталось",
    whatToWrite = "Что написать", topicPlaceholder = "Опишите тему документа, напр.\n\"Бизнес-план для эко-кафе\"",
    uploadFile = "Загрузить файл (необязательно)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Формат вывода", language = "Язык", generateDocuments = "Создать документы",
    minCharsHint = "Введите минимум 3 символа или загрузите файл",
    processing = "Обработка", generating = "Создаём ваши документы…",
    yourDocuments = "Ваши документы", filesReady = "Файлы готовы!",
    download = "Скачать", downloadAll = "Скачать всё", preview = "Предпросмотр", editDocument = "Редактировать",
    share = "Поделиться", createNew = "Создать новый",
    savedToDownloads = "Сохранено в Загрузки", saveFailed = "Ошибка сохранения", noFiles = "Нет файлов",
    settings = "Настройки", customizeExperience = "Настройте под себя",
    appearance = "Оформление", theme = "Тема", light = "Светлая", dark = "Тёмная", auto = "Авто",
    appLanguage = "Язык приложения", languageHint = "Изменить язык интерфейса",
    usage = "Использование", dailyTokenUsage = "Ежедневное использование", resetsAtMidnight = "Сброс в полночь",
    premium = "Премиум", premiumDesc = "Безлимитные токены и больше", soon = "Скоро",
    legal = "Правовая информация", privacyPolicy = "Политика конфиденциальности", privacyDesc = "Как мы обрабатываем данные",
    termsOfService = "Условия использования", termsDesc = "Правила использования AI Writer",
    sendFeedback = "Отправить отзыв", feedbackDesc = "Помогите улучшить AI Writer",
    history = "История", noHistory = "Документов пока нет",
    translate = "Перевод", aiTranslator = "AI Переводчик", translateSubtitle = "Переводите документы или текст с помощью ИИ",
    from = "С", to = "На", sourceLanguage = "Исходный язык", targetLanguage = "Целевой язык",
    enterText = "Введите или вставьте текст…", parsingFile = "Анализ файла…",
    summarize = "Резюме", aiSummarizer = "AI Резюматор", summarizeSubtitle = "Резюмируйте документы или текст с помощью ИИ",
    enterTextToSummarize = "Введите текст для резюмирования…", outputLanguage = "Язык вывода",
    howItWorks = "Как это работает", howItWorksDesc = "ИИ извлекает ключевые моменты из текста (30-40% от оригинала).",
    clearHistory = "Очистить историю", clearHistoryConfirm = "Удалить всю историю? Это необратимо.",
    clear = "Очистить", cancel = "Отмена", clearAll = "Очистить всё", historyEmpty = "Созданные документы появятся здесь",
    analyzingInput = "Анализ ввода", checkingLimits = "Проверка лимитов",
    generatingWithAi = "Генерация с ИИ", preparingEditor = "Подготовка редактора",
    dailyLimitReached = "Дневной лимит исчерпан. Попробуйте завтра.",
    generationFailed = "Ошибка генерации", errorOccurred = "Произошла ошибка", goBack = "Назад",
    getStarted = "Начать", welcomeTo = "Добро пожаловать в", aiWriter = "AI Writer",
    splashSubtitle = "Создавайте красивые документы\nс помощью ИИ",
    splashFeature1 = "PDF, Word, PPT и Excel",
    splashFeature2 = "Перевод на 32 языка",
    splashFeature3 = "ИИ-резюме и редактирование",
    appVersion = "AI Writer v3.0.0", poweredBy = "На базе Longcat AI"
)

val HindiStrings = Strings(
    navCreate = "बनाएँ", navSummary = "सारांश", navTranslate = "अनुवाद", navHistory = "इतिहास", navSettings = "सेटिंग्स",
    homeTitle = "AI Writer", homeSubtitle = "कुछ शानदार बनाएँ",
    dailyCredits = "दैनिक क्रेडिट", tokensRemaining = "टोकन शेष",
    whatToWrite = "क्या लिखें", topicPlaceholder = "दस्तावेज़ का विषय बताएँ\nजैसे: \"इको-फ्रेंडली कैफ़े बिज़नेस प्लान\"",
    uploadFile = "फ़ाइल अपलोड करें (वैकल्पिक)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "आउटपुट फ़ॉर्मैट", language = "भाषा", generateDocuments = "दस्तावेज़ बनाएँ",
    minCharsHint = "कम से कम 3 अक्षर दर्ज करें या फ़ाइल अपलोड करें",
    processing = "प्रोसेसिंग", generating = "आपके दस्तावेज़ बन रहे हैं…",
    yourDocuments = "आपके दस्तावेज़", filesReady = "फ़ाइलें तैयार हैं!",
    download = "डाउनलोड", downloadAll = "सभी डाउनलोड", preview = "प्रीव्यू", editDocument = "दस्तावेज़ संपादित करें",
    share = "शेयर", createNew = "नया बनाएँ",
    savedToDownloads = "डाउनलोड में सहेजा गया", saveFailed = "सहेजना विफल", noFiles = "कोई फ़ाइल नहीं",
    settings = "सेटिंग्स", customizeExperience = "अनुभव कस्टमाइज़ करें",
    appearance = "दिखावट", theme = "थीम", light = "लाइट", dark = "डार्क", auto = "ऑटो",
    appLanguage = "ऐप भाषा", languageHint = "डिस्प्ले भाषा बदलें",
    usage = "उपयोग", dailyTokenUsage = "दैनिक टोकन उपयोग", resetsAtMidnight = "मध्यरात्रि में रीसेट",
    premium = "प्रीमियम", premiumDesc = "असीमित टोकन और अधिक", soon = "जल्द",
    legal = "कानूनी", privacyPolicy = "गोपनीयता नीति", privacyDesc = "हम आपका डेटा कैसे संभालते हैं",
    termsOfService = "सेवा की शर्तें", termsDesc = "AI Writer उपयोग नियम",    sendFeedback = "प्रतिक्रियू भेजें", feedbackDesc = "AI Writer को बेहतर बनधने में मदद करें",    history = "इतिहास", noHistory = "अभी कोई दस्तावेज़ नहीं",
    translate = "अनुवाद", aiTranslator = "AI अनुवादक", translateSubtitle = "AI से दस्तावेज़ या टेक्स्ट अनुवाद करें",
    from = "से", to = "में", sourceLanguage = "स्रोत भाषा", targetLanguage = "लक्ष्य भाषा",
    enterText = "टेक्स्ट दर्ज करें या पेस्ट करें…", parsingFile = "फ़ाइल पार्स हो रही है…",
    summarize = "सारांश", aiSummarizer = "AI सारांशकर्ता", summarizeSubtitle = "AI से दस्तावेज़ या टेक्स्ट का सारांश करें",
    enterTextToSummarize = "सारांश के लिए टेक्स्ट दर्ज करें…", outputLanguage = "आउटपुट भाषा",
    howItWorks = "कैसे काम करता है", howItWorksDesc = "AI आपके टेक्स्ट से मुख्य बिंदु निकालता है (मूल लंबाई का 30-40%)।",
    clearHistory = "इतिहास साफ़ करें", clearHistoryConfirm = "सभी इतिहास हटाएँ? यह पूर्ववत नहीं किया जा सकता।",
    clear = "साफ़ करें", cancel = "रद्द करें", clearAll = "सभी साफ़ करें", historyEmpty = "बनाए गए दस्तावेज़ यहाँ दिखेंगे",
    analyzingInput = "इनपुट विश्लेषण", checkingLimits = "सीमाएँ जाँच रहे हैं",
    generatingWithAi = "AI से बना रहे हैं", preparingEditor = "एडिटर तैयार कर रहे हैं",
    dailyLimitReached = "दैनिक सीमा पूरी हुई। कल फिर प्रयास करें।",
    generationFailed = "निर्माण विफल", errorOccurred = "कोई त्रुटि हुई", goBack = "वापस जाएँ",
    getStarted = "शुरू करें", welcomeTo = "स्वागत है", aiWriter = "AI Writer",
    splashSubtitle = "AI की शक्ति से\nसुंदर दस्तावेज़ बनाएँ",
    splashFeature1 = "PDF, Word, PPT और Excel बनाएँ",
    splashFeature2 = "32 भाषाओं में अनुवाद",
    splashFeature3 = "AI सारांश और संपादन",
    appVersion = "AI Writer v3.0.0", poweredBy = "Longcat AI द्वारा संचालित"
)

val PortugueseStrings = Strings(
    navCreate = "Criar", navSummary = "Resumo", navTranslate = "Traduzir", navHistory = "Histórico", navSettings = "Configurações",
    homeTitle = "AI Writer", homeSubtitle = "Crie algo incrível",
    dailyCredits = "Créditos diários", tokensRemaining = "tokens restantes",
    whatToWrite = "O que escrever", topicPlaceholder = "Descreva o tema do documento, ex.\n\"Plano de negócios para café ecológico\"",
    uploadFile = "Enviar arquivo (opcional)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Formato de saída", language = "Idioma", generateDocuments = "Gerar documentos",
    minCharsHint = "Digite pelo menos 3 caracteres ou envie um arquivo",
    processing = "Processando", generating = "Gerando seus documentos…",
    yourDocuments = "Seus documentos", filesReady = "Seus arquivos estão prontos!",
    download = "Baixar", downloadAll = "Baixar tudo", preview = "Visualizar", editDocument = "Editar documento",
    share = "Compartilhar", createNew = "Criar novo",
    savedToDownloads = "Salvo em Downloads", saveFailed = "Falha ao salvar", noFiles = "Sem arquivos",
    settings = "Configurações", customizeExperience = "Personalize sua experiência",
    appearance = "Aparência", theme = "Tema", light = "Claro", dark = "Escuro", auto = "Auto",
    appLanguage = "Idioma do app", languageHint = "Alterar idioma da interface",
    usage = "Uso", dailyTokenUsage = "Uso diário de tokens", resetsAtMidnight = "Reseta à meia-noite",
    premium = "Premium", premiumDesc = "Tokens ilimitados e mais recursos", soon = "Em breve",
    legal = "Legal", privacyPolicy = "Política de Privacidade", privacyDesc = "Como tratamos seus dados",
    termsOfService = "Termos de Serviço", termsDesc = "Regras de uso do AI Writer",
    sendFeedback = "Enviar Feedback", feedbackDesc = "Ajude-nos a melhorar o AI Writer",
    history = "Histórico", noHistory = "Nenhum documento ainda",
    translate = "Traduzir", aiTranslator = "Tradutor AI", translateSubtitle = "Traduza documentos ou texto com IA",
    from = "De", to = "Para", sourceLanguage = "Idioma de origem", targetLanguage = "Idioma de destino",
    enterText = "Digite ou cole texto…", parsingFile = "Analisando arquivo…",
    summarize = "Resumir", aiSummarizer = "Resumidor AI", summarizeSubtitle = "Resuma documentos ou texto com IA",
    enterTextToSummarize = "Digite ou cole texto para resumir…", outputLanguage = "Idioma de saída",
    howItWorks = "Como funciona", howItWorksDesc = "A IA extrai os pontos-chave do seu texto, visando 30-40% do comprimento original.",
    clearHistory = "Limpar histórico", clearHistoryConfirm = "Excluir todo o histórico? Não pode ser desfeito.",
    clear = "Limpar", cancel = "Cancelar", clearAll = "Limpar tudo", historyEmpty = "Documentos gerados aparecerão aqui",
    analyzingInput = "Analisando entrada", checkingLimits = "Verificando limites",
    generatingWithAi = "Gerando com IA", preparingEditor = "Preparando editor",
    dailyLimitReached = "Limite diário atingido. Tente amanhã.",
    generationFailed = "Falha na geração", errorOccurred = "Ocorreu um erro", goBack = "Voltar",
    getStarted = "Começar", welcomeTo = "Bem-vindo ao", aiWriter = "AI Writer",
    splashSubtitle = "Crie belos documentos\ncom o poder da IA",
    splashFeature1 = "Gere PDF, Word, PPT e Excel",
    splashFeature2 = "Traduza documentos em 32 idiomas",
    splashFeature3 = "Resumos e edição com IA",
    appVersion = "AI Writer v3.0.0", poweredBy = "Desenvolvido com Longcat AI"
)

val ItalianStrings = Strings(
    navCreate = "Crea", navSummary = "Riassunto", navTranslate = "Traduci", navHistory = "Cronologia", navSettings = "Impostazioni",
    homeTitle = "AI Writer", homeSubtitle = "Crea qualcosa di straordinario",
    dailyCredits = "Crediti giornalieri", tokensRemaining = "token rimanenti",
    whatToWrite = "Cosa scrivere", topicPlaceholder = "Descrivi l'argomento del documento, es.\n\"Business plan per un caffè ecologico\"",
    uploadFile = "Carica file (opzionale)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Formato di output", language = "Lingua", generateDocuments = "Genera documenti",
    minCharsHint = "Inserisci almeno 3 caratteri o carica un file",
    processing = "Elaborazione", generating = "Generazione dei tuoi documenti…",
    yourDocuments = "I tuoi documenti", filesReady = "I tuoi file sono pronti!",
    download = "Scarica", downloadAll = "Scarica tutto", preview = "Anteprima", editDocument = "Modifica documento",
    share = "Condividi", createNew = "Crea nuovo",
    savedToDownloads = "Salvato nei Download", saveFailed = "Salvataggio fallito", noFiles = "Nessun file",
    settings = "Impostazioni", customizeExperience = "Personalizza la tua esperienza",
    appearance = "Aspetto", theme = "Tema", light = "Chiaro", dark = "Scuro", auto = "Auto",
    appLanguage = "Lingua dell'app", languageHint = "Cambia lingua dell'interfaccia",
    usage = "Utilizzo", dailyTokenUsage = "Utilizzo giornaliero token", resetsAtMidnight = "Si resetta a mezzanotte",
    premium = "Premium", premiumDesc = "Token illimitati e altro", soon = "Presto",
    legal = "Legale", privacyPolicy = "Informativa sulla Privacy", privacyDesc = "Come gestiamo i tuoi dati",
    termsOfService = "Termini di Servizio", termsDesc = "Regole di utilizzo di AI Writer",
    sendFeedback = "Invia Feedback", feedbackDesc = "Aiutaci a migliorare AI Writer",
    history = "Cronologia", noHistory = "Nessun documento ancora",
    translate = "Traduci", aiTranslator = "Traduttore AI", translateSubtitle = "Traduci documenti o testo con l'IA",
    from = "Da", to = "A", sourceLanguage = "Lingua di origine", targetLanguage = "Lingua di destinazione",
    enterText = "Inserisci o incolla testo…", parsingFile = "Analisi del file…",
    summarize = "Riassumi", aiSummarizer = "Riassuntore AI", summarizeSubtitle = "Riassumi documenti o testo con l'IA",
    enterTextToSummarize = "Inserisci testo da riassumere…", outputLanguage = "Lingua di output",
    howItWorks = "Come funziona", howItWorksDesc = "L'IA estrae i punti chiave dal tuo testo (30-40% della lunghezza originale).",
    clearHistory = "Cancella cronologia", clearHistoryConfirm = "Eliminare tutta la cronologia? Non è reversibile.",
    clear = "Cancella", cancel = "Annulla", clearAll = "Cancella tutto", historyEmpty = "I documenti generati appariranno qui",
    analyzingInput = "Analisi dell'input", checkingLimits = "Verifica dei limiti",
    generatingWithAi = "Generazione con IA", preparingEditor = "Preparazione dell'editor",
    dailyLimitReached = "Limite giornaliero raggiunto. Riprova domani.",
    generationFailed = "Generazione fallita", errorOccurred = "Si è verificato un errore", goBack = "Indietro",
    getStarted = "Inizia", welcomeTo = "Benvenuto su", aiWriter = "AI Writer",
    splashSubtitle = "Crea bellissimi documenti\ncon la potenza dell'IA",
    splashFeature1 = "Genera PDF, Word, PPT ed Excel",
    splashFeature2 = "Traduci documenti in 32 lingue",
    splashFeature3 = "Riassunti e modifica con IA",
    appVersion = "AI Writer v3.0.0", poweredBy = "Powered by Longcat AI"
)

val UrduStrings = Strings(
    navCreate = "بنائیں", navSummary = "خلاصہ", navTranslate = "ترجمہ", navHistory = "تاریخ", navSettings = "ترتیبات",
    homeTitle = "AI Writer", homeSubtitle = "کچھ شاندار بنائیں",
    dailyCredits = "روزانہ کریڈٹ", tokensRemaining = "ٹوکن باقی",
    whatToWrite = "کیا لکھیں", topicPlaceholder = "دستاویز کا موضوع بیان کریں\nمثال: \"ماحول دوست کیفے کا بزنس پلان\"",
    uploadFile = "فائل اپلوڈ کریں (اختیاری)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "آؤٹ پٹ فارمیٹ", language = "زبان", generateDocuments = "دستاویزات بنائیں",
    minCharsHint = "کم از کم 3 حروف درج کریں یا فائل اپلوڈ کریں",
    processing = "پروسیسنگ", generating = "آپ کی دستاویزات بنائی جا رہی ہیں…",
    yourDocuments = "آپ کی دستاویزات", filesReady = "فائلیں تیار ہیں!",
    download = "ڈاؤن لوڈ", downloadAll = "سب ڈاؤن لوڈ", preview = "پیش نظارہ", editDocument = "دستاویز میں ترمیم",
    share = "شیئر", createNew = "نیا بنائیں",
    savedToDownloads = "ڈاؤن لوڈز میں محفوظ", saveFailed = "محفوظ کرنا ناکام", noFiles = "کوئی فائل نہیں",
    settings = "ترتیبات", customizeExperience = "اپنا تجربہ حسب ضرورت بنائیں",
    appearance = "ظاہری شکل", theme = "تھیم", light = "ہلکا", dark = "گہرا", auto = "خودکار",
    appLanguage = "ایپ کی زبان", languageHint = "ڈسپلے زبان تبدیل کریں",
    usage = "استعمال", dailyTokenUsage = "روزانہ ٹوکن استعمال", resetsAtMidnight = "آدھی رات ری سیٹ",
    premium = "پریمیم", premiumDesc = "لامحدود ٹوکن اور مزید", soon = "جلد",
    legal = "قانونی", privacyPolicy = "رازداری پالیسی", privacyDesc = "ہم آپ کا ڈیٹا کیسے سنبھالتے ہیں",
    termsOfService = "سروس کی شرائط", termsDesc = "AI Writer استعمال کے قوانین",
    sendFeedback = "رائے بھیجیں", feedbackDesc = "AI Writer کو بہتر بنانے میں مدد کریں",
    history = "تاریخ", noHistory = "ابھی کوئی دستاویز نہیں",
    translate = "ترجمہ", aiTranslator = "AI مترجم", translateSubtitle = "AI سے دستاویزات یا متن کا ترجمہ کریں",
    from = "سے", to = "میں", sourceLanguage = "ماخذ زبان", targetLanguage = "ہدف زبان",
    enterText = "متن درج یا پیسٹ کریں…", parsingFile = "فائل تجزیہ ہو رہی ہے…",
    summarize = "خلاصہ", aiSummarizer = "AI خلاصہ ساز", summarizeSubtitle = "AI سے دستاویزات یا متن کا خلاصہ کریں",
    enterTextToSummarize = "خلاصے کے لیے متن درج کریں…", outputLanguage = "آؤٹ پٹ زبان",
    howItWorks = "یہ کیسے کام کرتا ہے", howItWorksDesc = "AI آپ کے متن سے اہم نکات نکالتا ہے (اصل لمبائی کا 30-40%)۔",
    clearHistory = "تاریخ صاف کریں", clearHistoryConfirm = "تمام تاریخ مٹائیں؟ یہ واپس نہیں ہو سکتا۔",
    clear = "صاف", cancel = "منسوخ", clearAll = "سب صاف", historyEmpty = "بنائی گئی دستاویزات یہاں دکھائی جائیں گی",
    analyzingInput = "ان پٹ تجزیہ", checkingLimits = "حدود چیک ہو رہی ہیں",
    generatingWithAi = "AI سے بنایا جا رہا ہے", preparingEditor = "ایڈیٹر تیار ہو رہا ہے",
    dailyLimitReached = "روزانہ حد پوری ہو گئی۔ کل دوبارہ کوشش کریں۔",
    generationFailed = "بنانا ناکام", errorOccurred = "کوئی خرابی ہوئی", goBack = "واپس جائیں",
    getStarted = "شروع کریں", welcomeTo = "خوش آمدید", aiWriter = "AI Writer",
    splashSubtitle = "AI کی طاقت سے\nخوبصورت دستاویزات بنائیں",
    splashFeature1 = "PDF، Word، PPT اور Excel بنائیں",
    splashFeature2 = "32 زبانوں میں ترجمہ",
    splashFeature3 = "AI خلاصہ اور ترمیم",
    appVersion = "AI Writer v3.0.0", poweredBy = "Longcat AI کی طرف سے"
)

fun getStringsForLanguage(code: String): Strings = when (code) {
    "ar" -> ArabicStrings
    "es" -> SpanishStrings
    "fr" -> FrenchStrings
    "de" -> GermanStrings
    "tr" -> TurkishStrings
    "fa" -> PersianStrings
    "ur" -> UrduStrings
    "zh" -> ChineseStrings
    "ja" -> JapaneseStrings
    "ko" -> KoreanStrings
    "ru" -> RussianStrings
    "hi" -> HindiStrings
    "pt" -> PortugueseStrings
    "it" -> ItalianStrings
    else -> EnglishStrings
}

val LocalStrings = compositionLocalOf { EnglishStrings }
