/**
 * AI Writer — Privacy Policy Screen
 */

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { useTheme } from '../utils/themeContext';

interface PrivacyScreenProps {
  navigation: any;
}

export default function PrivacyScreen({ navigation }: PrivacyScreenProps) {
  const { colors } = useTheme();

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: colors.background }]}
      contentContainerStyle={styles.scroll}
    >
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <Text style={[styles.backText, { color: colors.primary }]}>← Back</Text>
        </TouchableOpacity>
        <Text style={[styles.title, { color: colors.textPrimary }]}>🔒 Privacy Policy</Text>
        <Text style={[styles.lastUpdated, { color: colors.textMuted }]}>
          Last updated: February 14, 2026
        </Text>
      </View>

      {/* Content */}
      <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>1. Introduction</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          AI Writer ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy
          explains how we collect, use, disclose, and safeguard your information when you use our
          mobile application (the "App"). Please read this Privacy Policy carefully. By using the App,
          you agree to the collection and use of information in accordance with this policy.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>2. Information We Collect</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          <Text style={styles.bold}>Content Data:</Text> Topics you enter and files you upload are sent to our
          AI service (Longcat AI) for processing. This content is used solely to generate your requested documents.
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          <Text style={styles.bold}>Generated Files:</Text> Documents generated by the AI are stored locally
          on your device. We do not store copies of your generated files on our servers.
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          <Text style={styles.bold}>Usage Data:</Text> We may collect anonymous usage data such as app version,
          device type, operating system, and general usage patterns to improve the App experience.
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          <Text style={styles.bold}>Preferences:</Text> Your app settings such as language preference and theme
          choice are stored locally on your device.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>3. How We Use Your Information</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          We use the information we collect to:{'\n'}
          {'\n'}• Process your content through our AI service to generate documents
          {'\n'}• Improve and optimize the App's performance and features
          {'\n'}• Provide customer support
          {'\n'}• Monitor usage patterns and analytics (anonymized)
          {'\n'}• Communicate updates or changes to the App
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>4. Data Sharing & Third Parties</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          We do not sell, rent, or trade your personal information to third parties. Your content data
          is shared only with our AI processing partner (Longcat AI) for the sole purpose of generating
          your requested documents. We may share anonymized, aggregated data for analytics purposes.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>5. Data Security</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          We implement industry-standard security measures to protect your information. All data
          transmitted between the App and our servers is encrypted using TLS/SSL. However, no method
          of electronic transmission or storage is 100% secure, and we cannot guarantee absolute security.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>6. Data Retention</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          Content submitted for AI processing is not retained on our servers after document generation
          is complete. Generated files are stored locally on your device and can be deleted at any time
          through the App's History screen.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>7. Children's Privacy</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          The App is not intended for use by children under the age of 13. We do not knowingly collect
          personal information from children under 13. If we become aware that a child under 13 has
          provided us with personal information, we will take steps to delete such information.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>8. Your Rights</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          You have the right to:{'\n'}
          {'\n'}• Access, correct, or delete your personal data
          {'\n'}• Opt out of data collection where applicable
          {'\n'}• Request a copy of data we hold about you
          {'\n'}• Delete all locally stored data by clearing the App's data or uninstalling
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>9. Changes to This Policy</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          We may update this Privacy Policy from time to time. We will notify you of any changes by
          posting the new Privacy Policy in the App with an updated "Last updated" date. You are
          advised to review this Privacy Policy periodically for any changes.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>10. Contact Us</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          If you have any questions about this Privacy Policy, please contact us at:{'\n'}
          {'\n'}Email: privacy@aiwriter.app
          {'\n'}Website: https://aiwriter.app/privacy
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { padding: 20, paddingTop: 60, paddingBottom: 40 },
  header: { marginBottom: 20 },
  backBtn: { marginBottom: 12 },
  backText: { fontSize: 16, fontWeight: '500' },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 6 },
  lastUpdated: { fontSize: 12 },
  card: { borderRadius: 14, borderWidth: 1, padding: 20 },
  sectionHead: { fontSize: 16, fontWeight: '700', marginTop: 20, marginBottom: 8 },
  body: { fontSize: 14, lineHeight: 22, marginBottom: 8 },
  bold: { fontWeight: '600' },
});
