/**
 * AI Writer — Terms of Service Screen
 */

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { useTheme } from '../utils/themeContext';

interface TermsScreenProps {
  navigation: any;
}

export default function TermsScreen({ navigation }: TermsScreenProps) {
  const { colors } = useTheme();

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: colors.background }]}
      contentContainerStyle={styles.scroll}
    >
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <Text style={[styles.backText, { color: colors.primary }]}>← Back</Text>
        </TouchableOpacity>
        <Text style={[styles.title, { color: colors.textPrimary }]}>📋 Terms of Service</Text>
        <Text style={[styles.lastUpdated, { color: colors.textMuted }]}>
          Last updated: February 14, 2026
        </Text>
      </View>

      {/* Content */}
      <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>1. Acceptance of Terms</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          By downloading, installing, or using AI Writer (the "App"), you agree to be bound by these
          Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>2. Description of Service</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          AI Writer is a mobile application that uses artificial intelligence to generate professional
          documents (PDF, Word, PowerPoint, and Excel) based on user-provided topics or uploaded content.
          The App is provided "as is" and "as available."
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>3. User Responsibilities</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          You agree to:{'\n'}
          {'\n'}• Use the App only for lawful purposes
          {'\n'}• Not submit content that is illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable
          {'\n'}• Not attempt to reverse engineer, decompile, or disassemble the App
          {'\n'}• Not use the App to generate content that infringes on intellectual property rights
          {'\n'}• Not use automated systems or bots to access the App
          {'\n'}• Take responsibility for all content you submit and documents you generate
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>4. AI-Generated Content</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          Documents generated by AI Writer are produced by artificial intelligence and may contain
          inaccuracies, errors, or biases. You acknowledge that:{'\n'}
          {'\n'}• AI-generated content should be reviewed before professional use
          {'\n'}• We do not guarantee the accuracy, completeness, or suitability of generated content
          {'\n'}• You are solely responsible for verifying and editing generated content
          {'\n'}• AI Writer is a tool to assist, not replace, professional writing and review
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>5. Intellectual Property</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          You retain ownership of content you submit to the App. Documents generated by AI Writer
          based on your input become your property upon generation. The App itself, including its
          design, code, AI models, and branding, remains the intellectual property of AI Writer.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>6. Free & Premium Plans</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          AI Writer offers a free plan with limited features. Premium plans (when available) will be
          subject to additional terms and pricing. We reserve the right to modify plan limits, features,
          and pricing at any time. Users will be notified of significant changes in advance.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>7. Limitation of Liability</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          To the maximum extent permitted by applicable law, AI Writer and its developers shall not be
          liable for any indirect, incidental, special, consequential, or punitive damages, including
          but not limited to loss of profits, data, use, or other intangible losses arising from:{'\n'}
          {'\n'}• Your use or inability to use the App
          {'\n'}• Any errors, inaccuracies, or omissions in AI-generated content
          {'\n'}• Unauthorized access to or alteration of your data
          {'\n'}• Any third-party conduct related to the App
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>8. Disclaimer of Warranties</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          The App is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind,
          whether express or implied, including but not limited to implied warranties of merchantability,
          fitness for a particular purpose, and non-infringement.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>9. Termination</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          We reserve the right to suspend or terminate your access to the App at any time, without
          prior notice or liability, for any reason, including breach of these Terms. Upon termination,
          your right to use the App will cease immediately. Locally stored files will remain on your device.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>10. Governing Law</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          These Terms shall be governed by and construed in accordance with applicable laws, without
          regard to conflict of law principles. Any disputes arising from these Terms shall be resolved
          through binding arbitration.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>11. Changes to Terms</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          We may update these Terms from time to time. The updated version will be indicated by an
          updated "Last updated" date. Continued use of the App after changes constitutes acceptance
          of the revised Terms.
        </Text>

        <Text style={[styles.sectionHead, { color: colors.textPrimary }]}>12. Contact</Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          If you have any questions about these Terms of Service, please contact us at:{'\n'}
          {'\n'}Email: legal@aiwriter.app
          {'\n'}Website: https://ai-writer-2v9.pages.dev/terms
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { padding: 20, paddingTop: 60, paddingBottom: 40 },
  header: { marginBottom: 20 },
  backBtn: { marginBottom: 12 },
  backText: { fontSize: 16, fontWeight: '500' },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 6 },
  lastUpdated: { fontSize: 12 },
  card: { borderRadius: 14, borderWidth: 1, padding: 20 },
  sectionHead: { fontSize: 16, fontWeight: '700', marginTop: 20, marginBottom: 8 },
  body: { fontSize: 14, lineHeight: 22, marginBottom: 8 },
});
