package com.smartaiwriter.app.service

import com.smartaiwriter.app.data.remote.AiWriterOutput
import java.io.ByteArrayOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object XlsxGenerator {

    fun generate(output: AiWriterOutput): ByteArray {
        val headers = output.excel.headers
        val rows = output.excel.rows
        val title = output.pdfWord.title

        val baos = ByteArrayOutputStream()
        ZipOutputStream(baos).use { zip ->
            // [Content_Types].xml
            zip.putNextEntry(ZipEntry("[Content_Types].xml"))
            zip.write(contentTypes().toByteArray())
            zip.closeEntry()

            // _rels/.rels
            zip.putNextEntry(ZipEntry("_rels/.rels"))
            zip.write(rootRels().toByteArray())
            zip.closeEntry()

            // xl/workbook.xml
            zip.putNextEntry(ZipEntry("xl/workbook.xml"))
            zip.write(workbookXml().toByteArray())
            zip.closeEntry()

            // xl/_rels/workbook.xml.rels
            zip.putNextEntry(ZipEntry("xl/_rels/workbook.xml.rels"))
            zip.write(workbookRels().toByteArray())
            zip.closeEntry()

            // xl/styles.xml
            zip.putNextEntry(ZipEntry("xl/styles.xml"))
            zip.write(stylesXml().toByteArray())
            zip.closeEntry()

            // xl/sharedStrings.xml
            val allStrings = mutableListOf<String>()
            allStrings.add(title)
            allStrings.add("Generated by AI Writer")
            allStrings.addAll(headers)
            rows.forEach { row -> allStrings.addAll(row) }

            zip.putNextEntry(ZipEntry("xl/sharedStrings.xml"))
            zip.write(sharedStringsXml(allStrings).toByteArray())
            zip.closeEntry()

            // xl/worksheets/sheet1.xml
            zip.putNextEntry(ZipEntry("xl/worksheets/sheet1.xml"))
            zip.write(sheetXml(allStrings, headers, rows, title).toByteArray())
            zip.closeEntry()
        }
        return baos.toByteArray()
    }

    private fun esc(text: String): String = text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")

    private fun contentTypes(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
  <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>
</Types>"""

    private fun rootRels(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>"""

    private fun workbookXml(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets><sheet name="Data" sheetId="1" r:id="rId1"/></sheets>
</workbook>"""

    private fun workbookRels(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>
</Relationships>"""

    private fun stylesXml(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="3">
    <font><sz val="11"/><name val="Calibri"/><color rgb="FF1E1F23"/></font>
    <font><b/><sz val="16"/><name val="Calibri"/><color rgb="FFFFFFFF"/></font>
    <font><b/><sz val="11"/><name val="Calibri"/><color rgb="FFFFFFFF"/></font>
  </fonts>
  <fills count="4">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF353636"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFF0F0F2"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/><diagonal/></border>
    <border>
      <left style="thin"><color rgb="FFD8D8DC"/></left>
      <right style="thin"><color rgb="FFD8D8DC"/></right>
      <top style="thin"><color rgb="FFD8D8DC"/></top>
      <bottom style="thin"><color rgb="FFD8D8DC"/></bottom>
      <diagonal/>
    </border>
  </borders>
  <cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
  <cellXfs count="5">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="0" applyFont="1" applyFill="1"/>
    <xf numFmtId="0" fontId="2" fillId="2" borderId="1" applyFont="1" applyFill="1" applyBorder="1"/>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="1" applyBorder="1"/>
    <xf numFmtId="0" fontId="0" fillId="3" borderId="1" applyFill="1" applyBorder="1"/>
  </cellXfs>
</styleSheet>"""

    private fun sharedStringsXml(strings: List<String>): String {
        val items = strings.joinToString("") { "<si><t>${esc(it)}</t></si>" }
        return """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${strings.size}" uniqueCount="${strings.size}">$items</sst>"""
    }

    private fun sheetXml(
        allStrings: List<String>,
        headers: List<String>,
        rows: List<List<String>>,
        title: String
    ): String {
        val sb = StringBuilder()
        sb.append("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <cols>""")
        // Set column widths
        val colCount = headers.size.coerceAtLeast(1)
        for (i in 1..colCount) {
            sb.append("""<col min="$i" max="$i" width="25" customWidth="1"/>""")
        }
        sb.append("</cols><sheetData>")

        var rowNum = 1
        var stringIdx = 0

        // Title row (merged concept - just put title in A1 with title style)
        sb.append("""<row r="$rowNum"><c r="A$rowNum" s="1" t="s"><v>$stringIdx</v></c></row>""")
        rowNum++; stringIdx++ // title

        // Subtitle row
        sb.append("""<row r="$rowNum"><c r="A$rowNum" s="0" t="s"><v>$stringIdx</v></c></row>""")
        rowNum++; stringIdx++ // subtitle

        // Spacer
        sb.append("""<row r="$rowNum"/>""")
        rowNum++

        // Header row
        sb.append("""<row r="$rowNum">""")
        for (col in headers.indices) {
            val colLetter = ('A' + col)
            sb.append("""<c r="$colLetter$rowNum" s="2" t="s"><v>$stringIdx</v></c>""")
            stringIdx++
        }
        sb.append("</row>")
        rowNum++

        // Data rows
        for ((rowIdx, row) in rows.withIndex()) {
            val style = if (rowIdx % 2 == 0) "3" else "4"
            sb.append("""<row r="$rowNum">""")
            for (col in row.indices) {
                val colLetter = ('A' + col)
                sb.append("""<c r="$colLetter$rowNum" s="$style" t="s"><v>$stringIdx</v></c>""")
                stringIdx++
            }
            sb.append("</row>")
            rowNum++
        }

        sb.append("</sheetData></worksheet>")
        return sb.toString()
    }
}
