package com.aiwriter.app.util

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.runtime.staticCompositionLocalOf

/** Reactive app language state — changes trigger recomposition */
object AppLanguageState {
    var languageCode by mutableStateOf("en")
}

data class Strings(
    // Bottom nav
    val navCreate: String,
    val navSummary: String,
    val navTranslate: String,
    val navHistory: String,
    val navSettings: String,

    // Home screen
    val homeTitle: String,
    val homeSubtitle: String,
    val dailyCredits: String,
    val tokensRemaining: String,
    val whatToWrite: String,
    val topicPlaceholder: String,
    val uploadFile: String,
    val uploadSupported: String,
    val outputFormat: String,
    val language: String,
    val generateDocuments: String,
    val minCharsHint: String,

    // Processing
    val processing: String,
    val generating: String,

    // Result
    val yourDocuments: String,
    val filesReady: String,
    val download: String,
    val downloadAll: String,
    val preview: String,
    val editDocument: String,
    val share: String,
    val createNew: String,
    val savedToDownloads: String,
    val saveFailed: String,
    val noFiles: String,

    // Settings
    val settings: String,
    val customizeExperience: String,
    val appearance: String,
    val theme: String,
    val light: String,
    val dark: String,
    val auto: String,
    val appLanguage: String,
    val languageHint: String,
    val usage: String,
    val dailyTokenUsage: String,
    val resetsAtMidnight: String,
    val premium: String,
    val premiumDesc: String,
    val soon: String,
    val legal: String,
    val privacyPolicy: String,
    val privacyDesc: String,
    val termsOfService: String,
    val termsDesc: String,

    // History
    val history: String,
    val noHistory: String,

    // Translate
    val translate: String,
    val aiTranslator: String,
    val translateSubtitle: String,
    val from: String,
    val to: String,
    val sourceLanguage: String,
    val targetLanguage: String,
    val enterText: String,
    val parsingFile: String,

    // Summarize
    val summarize: String,
    val aiSummarizer: String,
    val summarizeSubtitle: String,
    val enterTextToSummarize: String,
    val outputLanguage: String,
    val howItWorks: String,
    val howItWorksDesc: String,

    // History
    val clearHistory: String,
    val clearHistoryConfirm: String,
    val clear: String,
    val cancel: String,
    val clearAll: String,
    val historyEmpty: String,

    // Processing
    val analyzingInput: String,
    val checkingLimits: String,
    val generatingWithAi: String,
    val preparingEditor: String,
    val dailyLimitReached: String,
    val generationFailed: String,
    val errorOccurred: String,
    val goBack: String,

    // Splash
    val getStarted: String,
    val welcomeTo: String,
    val aiWriter: String,
    val splashSubtitle: String,
    val splashFeature1: String,
    val splashFeature2: String,
    val splashFeature3: String,

    // Footer
    val appVersion: String,
    val poweredBy: String
)

val EnglishStrings = Strings(
    navCreate = "Create", navSummary = "Summary", navTranslate = "Translate", navHistory = "History", navSettings = "Settings",
    homeTitle = "AI Writer", homeSubtitle = "Create something amazing",
    dailyCredits = "Daily Credits", tokensRemaining = "tokens remaining",
    whatToWrite = "What to write", topicPlaceholder = "Describe your document topic, e.g.\n\"A business plan for an eco-friendly café\"",
    uploadFile = "Upload a file (optional)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Output format", language = "Language", generateDocuments = "Generate Documents",
    minCharsHint = "Enter at least 3 characters or upload a file",
    processing = "Processing", generating = "Generating your documents…",
    yourDocuments = "Your Documents", filesReady = "Your files are ready!",
    download = "Download", downloadAll = "Download All", preview = "Preview", editDocument = "Edit Document",
    share = "Share", createNew = "Create New",
    savedToDownloads = "Saved to Downloads", saveFailed = "Save failed", noFiles = "No files generated",
    settings = "Settings", customizeExperience = "Customize your experience",
    appearance = "Appearance", theme = "Theme", light = "Light", dark = "Dark", auto = "Auto",
    appLanguage = "App Language", languageHint = "Changes app display language",
    usage = "Usage", dailyTokenUsage = "Daily Token Usage", resetsAtMidnight = "Resets at midnight",
    premium = "Premium", premiumDesc = "Unlimited tokens & more features", soon = "Soon",
    legal = "Legal", privacyPolicy = "Privacy Policy", privacyDesc = "How we handle your data",
    termsOfService = "Terms of Service", termsDesc = "Rules for using AI Writer",
    history = "History", noHistory = "No documents yet",
    translate = "Translate", aiTranslator = "AI Translator", translateSubtitle = "Translate documents or text with AI",
    from = "From", to = "To", sourceLanguage = "Source Language", targetLanguage = "Target Language",
    enterText = "Enter or paste text…", parsingFile = "Parsing file…",
    summarize = "Summarize", aiSummarizer = "AI Summarizer", summarizeSubtitle = "Summarize documents or text with AI",
    enterTextToSummarize = "Enter or paste text to summarize…", outputLanguage = "Output Language",
    howItWorks = "How it works", howItWorksDesc = "AI extracts key points from your text, targeting 30-40% of original length.",
    clearHistory = "Clear History", clearHistoryConfirm = "Delete all history entries? This cannot be undone.",
    clear = "Clear", cancel = "Cancel", clearAll = "Clear All", historyEmpty = "Generated documents will appear here",
    analyzingInput = "Analyzing input", checkingLimits = "Checking usage limits",
    generatingWithAi = "Generating with AI", preparingEditor = "Preparing editor",
    dailyLimitReached = "Daily token limit reached. Try again tomorrow.",
    generationFailed = "Generation failed", errorOccurred = "An error occurred", goBack = "Go Back",
    getStarted = "Get Started", welcomeTo = "Welcome to", aiWriter = "AI Writer",
    splashSubtitle = "Create beautiful documents\nwith the power of AI",
    splashFeature1 = "Generate PDF, Word, PPT & Excel",
    splashFeature2 = "Translate documents in 32 languages",
    splashFeature3 = "AI-powered summaries & editing",
    appVersion = "AI Writer v2.0.0", poweredBy = "Powered by Longcat AI"
)

val ArabicStrings = Strings(
    navCreate = "إنشاء", navSummary = "ملخص", navTranslate = "ترجمة", navHistory = "السجل", navSettings = "الإعدادات",
    homeTitle = "AI Writer", homeSubtitle = "أنشئ شيئاً مذهلاً",
    dailyCredits = "الرصيد اليومي", tokensRemaining = "رمز متبقي",
    whatToWrite = "ماذا تريد أن تكتب", topicPlaceholder = "صف موضوع المستند، مثلاً\n\"خطة عمل لمقهى صديق للبيئة\"",
    uploadFile = "ارفع ملفاً (اختياري)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "صيغة الإخراج", language = "اللغة", generateDocuments = "إنشاء المستندات",
    minCharsHint = "أدخل 3 أحرف على الأقل أو ارفع ملفاً",
    processing = "جاري المعالجة", generating = "جاري إنشاء مستنداتك…",
    yourDocuments = "مستنداتك", filesReady = "ملفاتك جاهزة!",
    download = "تحميل", downloadAll = "تحميل الكل", preview = "معاينة", editDocument = "تعديل المستند",
    share = "مشاركة", createNew = "إنشاء جديد",
    savedToDownloads = "تم الحفظ في التنزيلات", saveFailed = "فشل الحفظ", noFiles = "لا توجد ملفات",
    settings = "الإعدادات", customizeExperience = "خصّص تجربتك",
    appearance = "المظهر", theme = "السمة", light = "فاتح", dark = "داكن", auto = "تلقائي",
    appLanguage = "لغة التطبيق", languageHint = "تغيير لغة عرض التطبيق",
    usage = "الاستخدام", dailyTokenUsage = "الاستخدام اليومي", resetsAtMidnight = "يتم إعادة التعيين عند منتصف الليل",
    premium = "مميز", premiumDesc = "رموز غير محدودة وميزات أكثر", soon = "قريباً",
    legal = "قانوني", privacyPolicy = "سياسة الخصوصية", privacyDesc = "كيف نتعامل مع بياناتك",
    termsOfService = "شروط الخدمة", termsDesc = "قواعد استخدام AI Writer",
    history = "السجل", noHistory = "لا توجد مستندات بعد",
    translate = "ترجمة", aiTranslator = "مترجم AI", translateSubtitle = "ترجم المستندات أو النصوص بالذكاء الاصطناعي",
    from = "من", to = "إلى", sourceLanguage = "اللغة المصدر", targetLanguage = "اللغة الهدف",
    enterText = "أدخل أو الصق نص…", parsingFile = "جاري تحليل الملف…",
    summarize = "تلخيص", aiSummarizer = "ملخص AI", summarizeSubtitle = "لخص المستندات أو النصوص بالذكاء الاصطناعي",
    enterTextToSummarize = "أدخل أو الصق نصاً لتلخيصه…", outputLanguage = "لغة الإخراج",
    howItWorks = "كيف يعمل", howItWorksDesc = "يستخرج الذكاء الاصطناعي النقاط الرئيسية من نصك بنسبة 30-40٪ من الطول الأصلي.",
    clearHistory = "مسح السجل", clearHistoryConfirm = "حذف جميع السجلات؟ لا يمكن التراجع.",
    clear = "مسح", cancel = "إلغاء", clearAll = "مسح الكل", historyEmpty = "ستظهر المستندات المنشأة هنا",
    analyzingInput = "تحليل المدخلات", checkingLimits = "التحقق من حدود الاستخدام",
    generatingWithAi = "الإنشاء بالذكاء الاصطناعي", preparingEditor = "تحضير المحرر",
    dailyLimitReached = "تم الوصول للحد اليومي. حاول غداً.",
    generationFailed = "فشل الإنشاء", errorOccurred = "حدث خطأ", goBack = "رجوع",
    getStarted = "ابدأ الآن", welcomeTo = "مرحباً بك في", aiWriter = "AI Writer",
    splashSubtitle = "أنشئ مستندات جميلة\nبقوة الذكاء الاصطناعي",
    splashFeature1 = "إنشاء PDF و Word و PPT و Excel",
    splashFeature2 = "ترجمة المستندات بـ 32 لغة",
    splashFeature3 = "تلخيص وتحرير بالذكاء الاصطناعي",
    appVersion = "AI Writer v2.0.0", poweredBy = "مدعوم بـ Longcat AI"
)

val SpanishStrings = Strings(
    navCreate = "Crear", navSummary = "Resumen", navTranslate = "Traducir", navHistory = "Historial", navSettings = "Ajustes",
    homeTitle = "AI Writer", homeSubtitle = "Crea algo increíble",
    dailyCredits = "Créditos diarios", tokensRemaining = "tokens restantes",
    whatToWrite = "Qué escribir", topicPlaceholder = "Describe el tema del documento, ej.\n\"Un plan de negocio para un café ecológico\"",
    uploadFile = "Subir archivo (opcional)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Formato de salida", language = "Idioma", generateDocuments = "Generar documentos",
    minCharsHint = "Ingresa al menos 3 caracteres o sube un archivo",
    processing = "Procesando", generating = "Generando tus documentos…",
    yourDocuments = "Tus documentos", filesReady = "¡Tus archivos están listos!",
    download = "Descargar", downloadAll = "Descargar todo", preview = "Vista previa", editDocument = "Editar documento",
    share = "Compartir", createNew = "Crear nuevo",
    savedToDownloads = "Guardado en Descargas", saveFailed = "Error al guardar", noFiles = "No hay archivos",
    settings = "Ajustes", customizeExperience = "Personaliza tu experiencia",
    appearance = "Apariencia", theme = "Tema", light = "Claro", dark = "Oscuro", auto = "Auto",
    appLanguage = "Idioma de la app", languageHint = "Cambiar idioma de la interfaz",
    usage = "Uso", dailyTokenUsage = "Uso diario de tokens", resetsAtMidnight = "Se reinicia a medianoche",
    premium = "Premium", premiumDesc = "Tokens ilimitados y más funciones", soon = "Pronto",
    legal = "Legal", privacyPolicy = "Política de privacidad", privacyDesc = "Cómo manejamos tus datos",
    termsOfService = "Términos de servicio", termsDesc = "Reglas de uso de AI Writer",
    history = "Historial", noHistory = "Aún no hay documentos",
    translate = "Traducir", aiTranslator = "Traductor AI", translateSubtitle = "Traduce documentos o texto con IA",
    from = "De", to = "A", sourceLanguage = "Idioma de origen", targetLanguage = "Idioma de destino",
    enterText = "Ingresa o pega texto…", parsingFile = "Analizando archivo…",
    summarize = "Resumir", aiSummarizer = "Resumidor AI", summarizeSubtitle = "Resume documentos o texto con IA",
    enterTextToSummarize = "Ingresa o pega texto para resumir…", outputLanguage = "Idioma de salida",
    howItWorks = "Cómo funciona", howItWorksDesc = "La IA extrae los puntos clave de tu texto, apuntando al 30-40% del largo original.",
    clearHistory = "Borrar historial", clearHistoryConfirm = "¿Eliminar todo el historial? No se puede deshacer.",
    clear = "Borrar", cancel = "Cancelar", clearAll = "Borrar todo", historyEmpty = "Los documentos generados aparecerán aquí",
    analyzingInput = "Analizando entrada", checkingLimits = "Verificando límites",
    generatingWithAi = "Generando con IA", preparingEditor = "Preparando editor",
    dailyLimitReached = "Límite diario alcanzado. Intenta mañana.",
    generationFailed = "Error al generar", errorOccurred = "Ocurrió un error", goBack = "Volver",
    getStarted = "Empezar", welcomeTo = "Bienvenido a", aiWriter = "AI Writer",
    splashSubtitle = "Crea documentos hermosos\ncon el poder de la IA",
    splashFeature1 = "Genera PDF, Word, PPT y Excel",
    splashFeature2 = "Traduce documentos en 32 idiomas",
    splashFeature3 = "Resúmenes y edición con IA",
    appVersion = "AI Writer v2.0.0", poweredBy = "Desarrollado con Longcat AI"
)

val FrenchStrings = Strings(
    navCreate = "Créer", navSummary = "Résumé", navTranslate = "Traduire", navHistory = "Historique", navSettings = "Paramètres",
    homeTitle = "AI Writer", homeSubtitle = "Créez quelque chose d'incroyable",
    dailyCredits = "Crédits quotidiens", tokensRemaining = "jetons restants",
    whatToWrite = "Que voulez-vous écrire", topicPlaceholder = "Décrivez le sujet, ex.\n\"Un business plan pour un café écologique\"",
    uploadFile = "Télécharger un fichier (optionnel)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Format de sortie", language = "Langue", generateDocuments = "Générer les documents",
    minCharsHint = "Entrez au moins 3 caractères ou téléchargez un fichier",
    processing = "Traitement", generating = "Génération de vos documents…",
    yourDocuments = "Vos documents", filesReady = "Vos fichiers sont prêts!",
    download = "Télécharger", downloadAll = "Tout télécharger", preview = "Aperçu", editDocument = "Modifier le document",
    share = "Partager", createNew = "Nouveau",
    savedToDownloads = "Enregistré dans Téléchargements", saveFailed = "Échec de sauvegarde", noFiles = "Aucun fichier",
    settings = "Paramètres", customizeExperience = "Personnalisez votre expérience",
    appearance = "Apparence", theme = "Thème", light = "Clair", dark = "Sombre", auto = "Auto",
    appLanguage = "Langue de l'app", languageHint = "Changer la langue de l'interface",
    usage = "Utilisation", dailyTokenUsage = "Utilisation quotidienne", resetsAtMidnight = "Réinitialisation à minuit",
    premium = "Premium", premiumDesc = "Jetons illimités et plus", soon = "Bientôt",
    legal = "Juridique", privacyPolicy = "Politique de confidentialité", privacyDesc = "Comment nous gérons vos données",
    termsOfService = "Conditions d'utilisation", termsDesc = "Règles d'utilisation d'AI Writer",
    history = "Historique", noHistory = "Aucun document pour l'instant",
    translate = "Traduire", aiTranslator = "Traducteur AI", translateSubtitle = "Traduisez des documents ou du texte avec l'IA",
    from = "De", to = "Vers", sourceLanguage = "Langue source", targetLanguage = "Langue cible",
    enterText = "Entrez ou collez du texte…", parsingFile = "Analyse du fichier…",
    summarize = "Résumer", aiSummarizer = "Résumeur AI", summarizeSubtitle = "Résumez des documents ou du texte avec l'IA",
    enterTextToSummarize = "Entrez ou collez du texte à résumer…", outputLanguage = "Langue de sortie",
    howItWorks = "Comment ça marche", howItWorksDesc = "L'IA extrait les points clés de votre texte, visant 30-40% de la longueur originale.",
    clearHistory = "Effacer l'historique", clearHistoryConfirm = "Supprimer tout l'historique ? Cette action est irréversible.",
    clear = "Effacer", cancel = "Annuler", clearAll = "Tout effacer", historyEmpty = "Les documents générés apparaîtront ici",
    analyzingInput = "Analyse de l'entrée", checkingLimits = "Vérification des limites",
    generatingWithAi = "Génération avec l'IA", preparingEditor = "Préparation de l'éditeur",
    dailyLimitReached = "Limite quotidienne atteinte. Réessayez demain.",
    generationFailed = "Échec de génération", errorOccurred = "Une erreur est survenue", goBack = "Retour",
    getStarted = "Commencer", welcomeTo = "Bienvenue sur", aiWriter = "AI Writer",
    splashSubtitle = "Créez de beaux documents\navec la puissance de l'IA",
    splashFeature1 = "Générez PDF, Word, PPT et Excel",
    splashFeature2 = "Traduisez dans 32 langues",
    splashFeature3 = "Résumés et édition par IA",
    appVersion = "AI Writer v2.0.0", poweredBy = "Propulsé par Longcat AI"
)

val GermanStrings = Strings(
    navCreate = "Erstellen", navSummary = "Zusammen.", navTranslate = "Übersetzen", navHistory = "Verlauf", navSettings = "Einstellung.",
    homeTitle = "AI Writer", homeSubtitle = "Erstelle etwas Großartiges",
    dailyCredits = "Tägliches Guthaben", tokensRemaining = "Tokens übrig",
    whatToWrite = "Was schreiben", topicPlaceholder = "Beschreibe das Thema, z.B.\n\"Ein Businessplan für ein Öko-Café\"",
    uploadFile = "Datei hochladen (optional)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Ausgabeformat", language = "Sprache", generateDocuments = "Dokumente erstellen",
    minCharsHint = "Gib mindestens 3 Zeichen ein oder lade eine Datei hoch",
    processing = "Verarbeitung", generating = "Deine Dokumente werden erstellt…",
    yourDocuments = "Deine Dokumente", filesReady = "Deine Dateien sind fertig!",
    download = "Download", downloadAll = "Alle herunterladen", preview = "Vorschau", editDocument = "Dokument bearbeiten",
    share = "Teilen", createNew = "Neu erstellen",
    savedToDownloads = "In Downloads gespeichert", saveFailed = "Speichern fehlgeschlagen", noFiles = "Keine Dateien",
    settings = "Einstellungen", customizeExperience = "Passe dein Erlebnis an",
    appearance = "Darstellung", theme = "Design", light = "Hell", dark = "Dunkel", auto = "Auto",
    appLanguage = "App-Sprache", languageHint = "Anzeigesprache ändern",
    usage = "Nutzung", dailyTokenUsage = "Tägliche Token-Nutzung", resetsAtMidnight = "Setzt um Mitternacht zurück",
    premium = "Premium", premiumDesc = "Unbegrenzte Tokens & mehr", soon = "Bald",
    legal = "Rechtliches", privacyPolicy = "Datenschutz", privacyDesc = "Wie wir mit deinen Daten umgehen",
    termsOfService = "Nutzungsbedingungen", termsDesc = "Regeln für die Nutzung",
    history = "Verlauf", noHistory = "Noch keine Dokumente",
    translate = "Übersetzen", aiTranslator = "AI Übersetzer", translateSubtitle = "Übersetze Dokumente oder Text mit KI",
    from = "Von", to = "Nach", sourceLanguage = "Ausgangssprache", targetLanguage = "Zielsprache",
    enterText = "Text eingeben oder einfügen…", parsingFile = "Datei wird analysiert…",
    summarize = "Zusammenfassen", aiSummarizer = "AI Zusammenfasser", summarizeSubtitle = "Fasse Dokumente oder Text mit KI zusammen",
    enterTextToSummarize = "Text zum Zusammenfassen eingeben…", outputLanguage = "Ausgabesprache",
    howItWorks = "So funktioniert's", howItWorksDesc = "KI extrahiert Kernpunkte aus deinem Text (ca. 30-40% der Originallänge).",
    clearHistory = "Verlauf löschen", clearHistoryConfirm = "Gesamten Verlauf löschen? Dies kann nicht rückgängig gemacht werden.",
    clear = "Löschen", cancel = "Abbrechen", clearAll = "Alles löschen", historyEmpty = "Erstellte Dokumente erscheinen hier",
    analyzingInput = "Eingabe analysieren", checkingLimits = "Limits prüfen",
    generatingWithAi = "Mit KI generieren", preparingEditor = "Editor vorbereiten",
    dailyLimitReached = "Tägliches Limit erreicht. Versuche es morgen.",
    generationFailed = "Generierung fehlgeschlagen", errorOccurred = "Ein Fehler ist aufgetreten", goBack = "Zurück",
    getStarted = "Loslegen", welcomeTo = "Willkommen bei", aiWriter = "AI Writer",
    splashSubtitle = "Erstelle schöne Dokumente\nmit der Kraft der KI",
    splashFeature1 = "PDF, Word, PPT & Excel erstellen",
    splashFeature2 = "Dokumente in 32 Sprachen übersetzen",
    splashFeature3 = "KI-gestützte Zusammenfassungen & Bearbeitung",
    appVersion = "AI Writer v2.0.0", poweredBy = "Powered by Longcat AI"
)

val TurkishStrings = Strings(
    navCreate = "Oluştur", navSummary = "Özet", navTranslate = "Çeviri", navHistory = "Geçmiş", navSettings = "Ayarlar",
    homeTitle = "AI Writer", homeSubtitle = "Harika bir şey oluştur",
    dailyCredits = "Günlük Kredi", tokensRemaining = "jeton kaldı",
    whatToWrite = "Ne yazmak istiyorsun", topicPlaceholder = "Belge konusunu açıklayın, örn.\n\"Eko-dostu bir kafe için iş planı\"",
    uploadFile = "Dosya yükle (isteğe bağlı)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "Çıktı formatı", language = "Dil", generateDocuments = "Belge Oluştur",
    minCharsHint = "En az 3 karakter girin veya dosya yükleyin",
    processing = "İşleniyor", generating = "Belgeleriniz oluşturuluyor…",
    yourDocuments = "Belgeleriniz", filesReady = "Dosyalarınız hazır!",
    download = "İndir", downloadAll = "Hepsini İndir", preview = "Önizleme", editDocument = "Belgeyi Düzenle",
    share = "Paylaş", createNew = "Yeni Oluştur",
    savedToDownloads = "İndirilenler'e kaydedildi", saveFailed = "Kaydetme başarısız", noFiles = "Dosya yok",
    settings = "Ayarlar", customizeExperience = "Deneyimini özelleştir",
    appearance = "Görünüm", theme = "Tema", light = "Açık", dark = "Koyu", auto = "Otomatik",
    appLanguage = "Uygulama Dili", languageHint = "Arayüz dilini değiştir",
    usage = "Kullanım", dailyTokenUsage = "Günlük Token Kullanımı", resetsAtMidnight = "Gece yarısı sıfırlanır",
    premium = "Premium", premiumDesc = "Sınırsız token ve daha fazlası", soon = "Yakında",
    legal = "Yasal", privacyPolicy = "Gizlilik Politikası", privacyDesc = "Verilerinizi nasıl işliyoruz",
    termsOfService = "Kullanım Şartları", termsDesc = "AI Writer kullanım kuralları",
    history = "Geçmiş", noHistory = "Henüz belge yok",
    translate = "Çeviri", aiTranslator = "AI Çevirmen", translateSubtitle = "Belgeleri veya metni yapay zeka ile çevirin",
    from = "Kaynak", to = "Hedef", sourceLanguage = "Kaynak Dil", targetLanguage = "Hedef Dil",
    enterText = "Metin girin veya yapıştırın…", parsingFile = "Dosya analiz ediliyor…",
    summarize = "Özetle", aiSummarizer = "AI Özetleyici", summarizeSubtitle = "Belgeleri veya metni yapay zeka ile özetleyin",
    enterTextToSummarize = "Özetlenecek metni girin…", outputLanguage = "Çıktı Dili",
    howItWorks = "Nasıl çalışır", howItWorksDesc = "Yapay zeka metninizden anahtar noktaları çıkarır, orijinal uzunluğun %30-40'ını hedefler.",
    clearHistory = "Geçmişi Temizle", clearHistoryConfirm = "Tüm geçmiş silinsin mi? Bu geri alınamaz.",
    clear = "Temizle", cancel = "İptal", clearAll = "Tümünü Temizle", historyEmpty = "Oluşturulan belgeler burada görünecek",
    analyzingInput = "Girdi analiz ediliyor", checkingLimits = "Limitler kontrol ediliyor",
    generatingWithAi = "Yapay zeka ile oluşturuluyor", preparingEditor = "Editör hazırlanıyor",
    dailyLimitReached = "Günlük limit aşıldı. Yarın tekrar deneyin.",
    generationFailed = "Oluşturma başarısız", errorOccurred = "Bir hata oluştu", goBack = "Geri Dön",
    getStarted = "Başla", welcomeTo = "Hoş geldiniz", aiWriter = "AI Writer",
    splashSubtitle = "Yapay zekanın gücüyle\ngüzel belgeler oluşturun",
    splashFeature1 = "PDF, Word, PPT ve Excel oluşturun",
    splashFeature2 = "32 dilde belge çevirin",
    splashFeature3 = "Yapay zeka ile özetleme ve düzenleme",
    appVersion = "AI Writer v2.0.0", poweredBy = "Longcat AI ile desteklenmektedir"
)

val PersianStrings = Strings(
    navCreate = "ایجاد", navSummary = "خلاصه", navTranslate = "ترجمه", navHistory = "تاریخچه", navSettings = "تنظیمات",
    homeTitle = "AI Writer", homeSubtitle = "چیز شگفت‌انگیزی بسازید",
    dailyCredits = "اعتبار روزانه", tokensRemaining = "توکن باقیمانده",
    whatToWrite = "چه بنویسم", topicPlaceholder = "موضوع سند را توصیف کنید\n\"طرح کسب و کار برای کافه سبز\"",
    uploadFile = "آپلود فایل (اختیاری)", uploadSupported = "DOCX, PPTX, XLSX, TXT, CSV",
    outputFormat = "فرمت خروجی", language = "زبان", generateDocuments = "ایجاد اسناد",
    minCharsHint = "حداقل ۳ کاراکتر وارد کنید یا فایل آپلود کنید",
    processing = "در حال پردازش", generating = "در حال ایجاد اسناد شما…",
    yourDocuments = "اسناد شما", filesReady = "فایل‌های شما آماده‌اند!",
    download = "دانلود", downloadAll = "دانلود همه", preview = "پیش‌نمایش", editDocument = "ویرایش سند",
    share = "اشتراک", createNew = "ایجاد جدید",
    savedToDownloads = "در دانلودها ذخیره شد", saveFailed = "ذخیره ناموفق", noFiles = "فایلی نیست",
    settings = "تنظیمات", customizeExperience = "تجربه خود را سفارشی کنید",
    appearance = "ظاهر", theme = "تم", light = "روشن", dark = "تاریک", auto = "خودکار",
    appLanguage = "زبان برنامه", languageHint = "تغییر زبان نمایش",
    usage = "مصرف", dailyTokenUsage = "مصرف روزانه توکن", resetsAtMidnight = "نیمه‌شب بازنشانی می‌شود",
    premium = "ویژه", premiumDesc = "توکن نامحدود و امکانات بیشتر", soon = "به‌زودی",
    legal = "حقوقی", privacyPolicy = "سیاست حریم خصوصی", privacyDesc = "نحوه مدیریت داده‌های شما",
    termsOfService = "شرایط خدمات", termsDesc = "قوانین استفاده از AI Writer",
    history = "تاریخچه", noHistory = "هنوز سندی نیست",
    translate = "ترجمه", aiTranslator = "مترجم AI", translateSubtitle = "اسناد یا متن را با هوش مصنوعی ترجمه کنید",
    from = "از", to = "به", sourceLanguage = "زبان مبدا", targetLanguage = "زبان مقصد",
    enterText = "متن وارد کنید…", parsingFile = "در حال تحلیل فایل…",
    summarize = "خلاصه‌سازی", aiSummarizer = "خلاصه‌ساز AI", summarizeSubtitle = "اسناد یا متن را با هوش مصنوعی خلاصه کنید",
    enterTextToSummarize = "متن برای خلاصه‌سازی وارد کنید…", outputLanguage = "زبان خروجی",
    howItWorks = "نحوه کار", howItWorksDesc = "هوش مصنوعی نکات کلیدی را از متن شما استخراج می‌کند (۳۰-۴۰٪ طول اصلی).",
    clearHistory = "پاک کردن تاریخچه", clearHistoryConfirm = "همه تاریخچه پاک شود؟ این عمل قابل بازگشت نیست.",
    clear = "پاک کردن", cancel = "لغو", clearAll = "پاک کردن همه", historyEmpty = "اسناد ایجاد شده اینجا نمایش داده می‌شوند",
    analyzingInput = "تحلیل ورودی", checkingLimits = "بررسی محدودیت‌ها",
    generatingWithAi = "ایجاد با هوش مصنوعی", preparingEditor = "آماده‌سازی ویرایشگر",
    dailyLimitReached = "محدودیت روزانه پر شد. فردا دوباره تلاش کنید.",
    generationFailed = "ایجاد ناموفق", errorOccurred = "خطایی رخ داد", goBack = "بازگشت",
    getStarted = "شروع", welcomeTo = "خوش آمدید به", aiWriter = "AI Writer",
    splashSubtitle = "اسناد زیبا بسازید\nبا قدرت هوش مصنوعی",
    splashFeature1 = "ایجاد PDF، Word، PPT و Excel",
    splashFeature2 = "ترجمه اسناد به ۳۲ زبان",
    splashFeature3 = "خلاصه‌سازی و ویرایش با هوش مصنوعی",
    appVersion = "AI Writer v2.0.0", poweredBy = "ارائه شده توسط Longcat AI"
)

fun getStringsForLanguage(code: String): Strings = when (code) {
    "ar" -> ArabicStrings
    "es" -> SpanishStrings
    "fr" -> FrenchStrings
    "de" -> GermanStrings
    "tr" -> TurkishStrings
    "fa" -> PersianStrings
    "ur" -> ArabicStrings // Urdu uses Arabic strings as fallback
    else -> EnglishStrings
}

val LocalStrings = staticCompositionLocalOf { EnglishStrings }
